import test from 'node:test';
import assert from 'node:assert/strict';
import * as T from '../web/vendor/three.module.js';
import {freshState,parseSave} from '../web/realm/economy.js';
import {chooseArchetype,assignSpell,stats,SPELLS} from '../web/realm/rpg.js';
import {createCombat,TRAINING,isSanctuary} from '../web/realm/combat.js';
import {createSpellEffects} from '../web/realm/spell-effects.js';
import {createCombatGraphics} from '../web/realm/graphics.js';
import {createWorld,blocksAt,surfaceAt} from '../web/realm/world.js';
function setup(){const s=freshState();chooseArchetype(s,'wizard');s.position={x:0,z:-60,yaw:0,pitch:0};const events=[],world={colliders:[]};const c=createCombat({state:()=>s,world,emit:e=>events.push(e)});const enemy={id:'hostile-0',kind:'goblin',name:'Goblin',x:0,z:-62,homeX:0,homeZ:-62,health:1000,maxHealth:1000,speed:0,damage:12,xp:10,coin:10,freeze:0,iceLock:0,chill:0,burn:0,bind:0,slow:0,attackTime:100,windup:0,flash:0,heading:0,dead:false};c.enemies.splice(0,c.enemies.length,enemy);return{s,c,enemy,events,world};}
function advance(c,seconds,dt=.05){for(let i=0;i<Math.round(seconds/dt);i++)c.update(dt);}
function cast(f,id){f.s.hero.cooldowns[id]=0;f.s.hero.mana=stats(f.s.hero).mana;assignSpell(f.s,0,id);assert.equal(f.c.cast(0).ok,true);}

test('burn damage is bounded and independent of .05 versus .1 second steps',()=>{for(const dt of [.05,.1]){const {c,enemy}=setup();enemy.burn=3;enemy.burnTick=0;enemy.burnDamage=4;advance(c,4,dt);assert.equal(enemy.health,988);assert.equal(enemy.burn,0);}});
test('frost and fire shatter once while preserving a separate roots immobilization',()=>{const f=setup();cast(f,'roots');cast(f,'frost');advance(f.c,.1);assert.ok(f.enemy.iceLock>0);assert.ok(f.enemy.freeze>0);cast(f,'fireball');advance(f.c,.1);assert.equal(f.events.filter(e=>e.type==='combo'&&e.combo==='shatter').length,1);assert.equal(f.enemy.iceLock,0);assert.equal(f.enemy.chill,0);assert.ok(f.enemy.freeze>4);assert.ok(f.enemy.burn>0);cast(f,'fireball');advance(f.c,.1);assert.equal(f.events.filter(e=>e.type==='combo').length,1);});
test('roots and weapon stagger alone do not enable an ice combination',()=>{const f=setup();f.enemy.freeze=8;cast(f,'fireball');advance(f.c,.1);assert.equal(f.events.some(e=>e.type==='combo'),false);assert.ok(f.enemy.freeze>7);});
test('lightning consumes chill for conduction but its own stun is not ice',()=>{const f=setup();f.enemy.chill=4;cast(f,'lightning');assert.equal(f.events.filter(e=>e.type==='combo'&&e.combo==='conduction').length,1);assert.equal(f.enemy.chill,0);cast(f,'lightning');assert.equal(f.events.filter(e=>e.type==='combo').length,1);});
test('ice extinguishes burns and periodic lethal damage awards one reward',()=>{const f=setup();f.enemy.burn=3;f.enemy.burnDamage=4;cast(f,'frost');advance(f.c,.1);assert.equal(f.enemy.burn,0);const g=setup();g.enemy.health=4;g.enemy.burn=3;g.enemy.burnDamage=4;g.enemy.burnTick=0;const coins=g.s.coins;advance(g.c,4);assert.equal(g.s.hero.kills,1);assert.equal(g.s.coins,coins+10);assert.ok(parseSave(JSON.stringify(g.s)));});
test('reapplying fire refreshes a bounded burn without stacking its rate',()=>{const f=setup();cast(f,'fireball');advance(f.c,.1);const rate=f.enemy.burnDamage;cast(f,'fireball');advance(f.c,.1);assert.equal(f.enemy.burnDamage,rate);assert.ok(f.enemy.burn<=3);const before=f.enemy.health;advance(f.c,4);assert.ok(before-f.enemy.health<=rate*3+1e-6);});
test('training targets take damage, reset, and never mutate progression',()=>{const s=freshState();chooseArchetype(s,'ogre');s.position={x:-15,z:19,yaw:0,pitch:0};const c=createCombat({state:()=>s,world:{colliders:[]}}),target=c.enemies.find(e=>e.id==='training-0'),before={coins:s.coins,kills:s.hero.kills,xp:s.hero.xp};target.health=1;assert.equal(c.attack().ok,true);assert.equal(target.dead,true);assert.deepEqual({coins:s.coins,kills:s.hero.kills,xp:s.hero.xp},before);assert.deepEqual(s.hero.defeated,{});advance(c,2.2);assert.equal(target.dead,false);assert.equal(target.health,target.maxHealth);assert.ok(parseSave(JSON.stringify(s)));});
test('practice focus requires proximity and restores only mana and spell readiness',()=>{const f=setup();f.s.hero.mana=0;f.s.hero.cooldowns.fireball=2;const hp=f.s.hero.health,coins=f.s.coins;assert.equal(f.c.practice().ok,false);assert.equal(f.s.hero.mana,0);f.s.position={...TRAINING.focus,yaw:0,pitch:0};assert.equal(f.c.practice().ok,true);assert.equal(f.s.hero.mana,stats(f.s.hero).mana);assert.equal(f.s.hero.cooldowns.fireball,0);assert.equal(f.s.hero.health,hp);assert.equal(f.s.coins,coins);});
test('enemy attack has a visible windup and evaluates guard at impact',()=>{const f=setup();f.enemy.attackTime=0;const hp=f.s.hero.health;f.c.update(.05);assert.equal(f.s.hero.health,hp);assert.ok(f.enemy.windup>0);advance(f.c,.5);assert.equal(f.s.hero.health,hp);f.c.setBlocking(true);advance(f.c,.2);assert.ok(f.s.hero.health<hp);assert.ok(hp-f.s.hero.health<12*stats(f.s.hero).armor*.4);assert.ok(f.events.some(e=>e.type==='guard'&&e.absorbed>0));});
test('incoming frost interrupts a pending strike before damage resolves',()=>{const f=setup();f.enemy.windup=.02;f.enemy.windupTotal=.65;const hp=f.s.hero.health;cast(f,'frost');f.c.update(.1);assert.equal(f.s.hero.health,hp);assert.equal(f.enemy.windup,0);assert.ok(f.events.some(e=>e.type==='telegraph'&&e.phase==='cancel'));});
test('sanctuary and line-of-sight changes cancel pending strikes',()=>{for(const kind of ['town','wall']){const f=setup();f.enemy.windup=.05;f.enemy.windupTotal=.65;if(kind==='town')f.s.position={x:0,z:0,yaw:0,pitch:0};else f.world.colliders.push({x1:-2,x2:2,z1:-61.2,z2:-60.8});const hp=f.s.hero.health;f.c.update(.1);assert.equal(f.s.hero.health,hp);assert.equal(f.enemy.windup,0);}});
test('ground targeting preview agrees with the selected area spell',()=>{const f=setup();assignSpell(f.s,0,'meteor');f.s.hero.selected=0;f.s.position.pitch=-.4;const aim=f.c.aim();assert.ok(aim&&aim.radius===SPELLS.meteor.radius);cast(f,'meteor');assert.equal(f.c.zones[0].x,aim.x);assert.equal(f.c.zones[0].z,aim.z);});
test('spell effects retain finite geometry, obey caps, pause and clear completely',()=>{const f=setup(),scene=new T.Scene(),fx=createSpellEffects(scene,{quality:'high'});for(const id of Object.keys(SPELLS)){if(id==='heal')f.s.hero.health-=10;cast(f,id);}for(const e of f.events)fx.emit(e);fx.update(.05,f.c);assert.ok(fx.counts.effects>0);const before=fx.counts;fx.update(0,f.c);assert.deepEqual(fx.counts,before);for(let i=0;i<100;i++)fx.emit({type:'impact',x:0,y:1,z:-62,color:0xffaa66,radius:6});fx.update(.05,f.c);assert.ok(fx.counts.effects<=48);assert.ok(fx.counts.particles<=1800);scene.traverse(o=>{if(o.geometry)for(const n of o.geometry.attributes.position.array)assert.ok(Number.isFinite(n));assert.ok(o.position.toArray().every(Number.isFinite));assert.ok(o.scale.toArray().every(Number.isFinite));});fx.clear();assert.deepEqual(fx.counts,{particles:0,effects:0,projectiles:0,telegraphs:0});fx.dispose();assert.equal(scene.children.length,0);});
test('practice targets and focus are clear of real world collision and graphics construct',()=>{const original=globalThis.document;globalThis.document={createElement(){return{width:0,height:0,getContext(){return{fillRect(){},strokeRect(){},fillText(){}};}};},querySelector(){return null;}};try{const scene=new T.Scene(),world=createWorld(scene),s=freshState();chooseArchetype(s,'wizard');const c=createCombat({state:()=>s,world});for(const p of [...TRAINING.targets,TRAINING.focus]){assert.equal(blocksAt(p.x,p.z,world.colliders),false);assert.equal(isSanctuary(p),true);}const gfx=createCombatGraphics(scene,new T.PerspectiveCamera(),()=>s,{quality:'low',reducedMotion:true});for(const e of c.enemies)e.chill=2;gfx.update(.05,0,c,true,false,false);assert.equal(gfx.enemyMeshes.size,17);scene.traverse(o=>assert.ok(o.matrix.elements.every(Number.isFinite)));}finally{globalThis.document=original;}});
