import test from 'node:test';
import assert from 'node:assert/strict';
import {GOODS,BIASES,freshState,quote,transact,harvest,questAction,upgrade,nextDay,rest,acceptContract,completeContract,contractOffer,parseSave,cargoUsed,checkGoal} from '../web/realm/economy.js';
import {createWorld,TOWNS,ROADS,heightAt,surfaceAt,blocksAt,moveWithCollision} from '../web/realm/world.js';
import * as T from '../web/vendor/three.module.js';

test('transactions reject malformed input atomically',()=>{for(const qty of [0,-1,1.5,NaN,Infinity,'1',1000]){const s=freshState(),before=JSON.stringify(s);assert.equal(transact(s,'eldermere','grain',qty,'buy').ok,false);assert.equal(JSON.stringify(s),before);}for(const [town,good,side]of [['bad','grain','buy'],['eldermere','bad','buy'],['eldermere','grain','hack']]){const s=freshState(),before=JSON.stringify(s);assert.equal(transact(s,town,good,1,side).ok,false);assert.equal(JSON.stringify(s),before);}});
test('trade charges displayed totals and conserves stock and owned goods',()=>{const s=freshState(),price=quote(s,'eldermere','grain','buy'),stock=s.stock.eldermere.grain;assert.equal(transact(s,'eldermere','grain',5,'buy').total,price*5);assert.equal(s.coins,120-price*5);assert.equal(s.inventory.grain,5);assert.equal(s.stock.eldermere.grain,stock-5);assert.equal(s.costBasis.grain,price*5);const sale=quote(s,'eldermere','grain','sell');assert.equal(transact(s,'eldermere','grain',2,'sell').total,sale*2);assert.equal(s.costBasis.grain,price*3);assert.equal(s.inventory.grain,3);assert.equal(s.stock.eldermere.grain,stock-3);});
test('no same-village buy/sell profit over a whole stock purchase',()=>{for(const town of Object.keys(BIASES))for(const good of Object.keys(GOODS)){const s=freshState();s.coins=100000;s.capacity=60;const before=s.coins;const qty=Math.min(30,s.stock[town][good]);assert.equal(transact(s,town,good,qty,'buy').ok,true);assert.equal(transact(s,town,good,qty,'sell').ok,true);assert.ok(s.coins<before,`${town} ${good} should lose money on a round trip`);}});
test('each settlement pair has a profitable export route',()=>{const s=freshState();const towns=Object.keys(BIASES);for(const from of towns)for(const to of towns){if(from===to)continue;assert.ok(Object.keys(GOODS).some(g=>quote(s,to,g,'sell')>quote(s,from,g,'buy')),`${from} → ${to}`);}});
test('stock, capacity, funds and owned quantity are hard constraints',()=>{for(const setup of [s=>s.coins=0,s=>s.inventory.wool=30,s=>s.stock.eldermere.grain=0]){const s=freshState();setup(s);const before=JSON.stringify(s);assert.equal(transact(s,'eldermere','grain',1,'buy').ok,false);assert.equal(JSON.stringify(s),before);}const s=freshState(),before=JSON.stringify(s);assert.equal(transact(s,'eldermere','iron',1,'sell').ok,false);assert.equal(JSON.stringify(s),before);});
test('harvest once per day, persists across reload, returns next day',()=>{let s=freshState();const node={id:'plant-0',kind:'herbs'};assert.equal(harvest(s,node).ok,true);assert.equal(s.inventory.herbs,2);s=parseSave(JSON.stringify(s));assert.ok(s);assert.equal(harvest(s,node).ok,false);nextDay(s);assert.equal(harvest(s,node).ok,true);assert.equal(s.inventory.herbs,4);s.inventory.wool=26;assert.equal(cargoUsed(s),30);assert.equal(harvest(s,{id:'plant-1',kind:'berries'}).ok,false);});
test('quest chain consumes exact goods and cannot pay twice after reload',()=>{let s=freshState();assert.equal(questAction(s,'elin').ok,false);assert.equal(questAction(s,'rowan').ok,true);assert.equal(s.quest,1);assert.equal(questAction(s,'elin').ok,false);s.inventory.herbs=4;s.costBasis.herbs=24;assert.equal(questAction(s,'elin').ok,true);assert.equal(s.inventory.herbs,1);assert.equal(s.costBasis.herbs,6);assert.equal(s.coins,165);s=parseSave(JSON.stringify(s));const before=s.coins;assert.equal(questAction(s,'elin').ok,false);assert.equal(s.coins,before);s.inventory.grain=6;assert.equal(questAction(s,'agnes').ok,true);s.inventory.iron=4;assert.equal(questAction(s,'rowan').ok,true);assert.equal(s.quest,4);s.coins=1000;s.visits=['eldermere','mossbrook'];assert.equal(checkGoal(s),false);s.visits.push('ironhold');assert.equal(checkGoal(s),true);assert.equal(checkGoal(s),false);assert.equal(s.quest,5);});
test('delivery rewards pay once at destination and include replacement value',()=>{let s=freshState();assert.equal(acceptContract(s,'mossbrook').ok,true);assert.equal(acceptContract(s,'mossbrook').ok,false);const c=s.contracts[0];assert.ok(c.reward>quote(s,'mossbrook',c.good,'buy')*c.qty);s.inventory[c.good]=c.qty;assert.equal(completeContract(s,c.id,'eldermere').ok,false);assert.equal(completeContract(s,c.id,'ironhold').ok,true);assert.equal(s.inventory[c.good],0);s=parseSave(JSON.stringify(s));const before=s.coins;assert.equal(completeContract(s,c.id,'ironhold').ok,false);assert.equal(s.coins,before);nextDay(s);assert.equal(acceptContract(s,'mossbrook').ok,true);});
test('sleep and pack upgrades charge once and respect limits',()=>{const s=freshState();assert.equal(upgrade(s).ok,true);assert.equal(s.coins,20);assert.equal(s.capacity,45);assert.equal(upgrade(s).ok,false);const stock=s.stock.eldermere.grain;assert.equal(rest(s).ok,true);assert.equal(s.day,2);assert.equal(s.coins,12);assert.equal(s.stock.eldermere.grain,stock+12);s.coins=7;const before=JSON.stringify(s);assert.equal(rest(s).ok,false);assert.equal(JSON.stringify(s),before);});
test('invalid and corrupt saves are rejected, valid full state round trips',()=>{const s=freshState();assert.deepEqual(parseSave(JSON.stringify(s)),s);for(const raw of ['bad','null','{}','[]'])assert.equal(parseSave(raw),null);const mutations=[s=>s.coins=-1,s=>s.position.x=2000,s=>s.inventory.iron=1.5,s=>s.inventory.unknown=3,s=>s.stock.eldermere.grain=-1,s=>s.quest=99,s=>s.contracts=[{id:'x'}],s=>s.harvested={'plant-1':999},s=>s.visits=['eldermere','eldermere']];for(const mutate of mutations){const bad=freshState();mutate(bad);assert.equal(parseSave(JSON.stringify(bad)),null);} });
// A minimal canvas context is enough to construct sign textures in Node. This is
// geometry/logic verification, not a claim of WebGL or browser UI verification.
const originalDocument=globalThis.document;
globalThis.document={createElement(tag){assert.equal(tag,'canvas');return{width:0,height:0,getContext(){return{fillRect(){},strokeRect(){},fillText(){}};}};}};
const scene=new T.Scene(),world=createWorld(scene);
globalThis.document=originalDocument;
test('world has 3 settlements, 12 physically enterable furnished houses, merchants and four species',()=>{assert.equal(TOWNS.length,3);assert.equal(world.houses.length,12);assert.equal(world.npcs.length,9);assert.deepEqual([...new Set(world.animals.map(a=>a.kind))].sort(),['chicken','deer','rabbit','sheep']);assert.ok(world.gatherables.length>=24);});
test('all doors block when closed and allow entry and exit when opened',()=>{for(const h of world.houses){const start={...h.entry};assert.equal(blocksAt(start.x,start.z,world.colliders),false,`${h.id} entry clear`);const center={x:h.group.position.x,z:h.group.position.z};const dx=center.x-start.x,dz=center.z-start.z;moveWithCollision(start,dx,dz,world.colliders);assert.equal(world.roomAt(start.x,start.z),null,`${h.id} closed`);assert.equal(world.toggleDoor(h),true);const p={...h.entry};const destination=new T.Vector3(0,0,2).applyAxisAngle(new T.Vector3(0,1,0),h.yaw).add(h.group.position);moveWithCollision(p,destination.x-p.x,destination.z-p.z,world.colliders);assert.equal(world.roomAt(p.x,p.z),h.id,`${h.id} open entry`);moveWithCollision(p,h.entry.x-p.x,h.entry.z-p.z,world.colliders);assert.equal(world.roomAt(p.x,p.z),null,`${h.id} exit`);world.toggleDoor(h);}});
test('doors cannot close on the player, and walls resist long sprint steps',()=>{const h=world.houses[0];world.toggleDoor(h);assert.equal(world.toggleDoor(h,{x:h.x,z:h.z}),false);assert.equal(h.open,true);assert.equal(world.toggleDoor(h,h.entry),true);const walls=[{x1:1,x2:2,z1:-5,z2:5}];const p={x:0,z:0};moveWithCollision(p,10,0,walls);assert.ok(p.x<.7);const slide={x:.6,z:0};moveWithCollision(slide,4,3,walls);assert.ok(slide.x<.7);assert.ok(slide.z>2.5);});
test('both bridges cross the river and use the raised walking surface',()=>{for(const z of [-55,32]){const p={x:45,z};moveWithCollision(p,22,0,world.colliders);assert.ok(p.x>65);assert.ok(surfaceAt(56,z)>heightAt(56,z)+.5);}const p={x:45,z:0};moveWithCollision(p,22,0,world.colliders);assert.ok(p.x<50);});
test('all settlement routes remain walkable along their road centerlines',()=>{for(const road of ROADS.slice(0,3)){const p={x:road[0][0],z:road[0][1]};for(const [x,z]of road.slice(1)){// The town well is deliberately off-center; road centerlines should remain clear.
 moveWithCollision(p,x-p.x,z-p.z,world.colliders);assert.ok(Math.hypot(p.x-x,p.z-z)<2,`Route stopped near ${p.x.toFixed(1)}, ${p.z.toFixed(1)} instead of ${x},${z}`);}}});
test('gatherable groups retain render transforms and dynamic animation stays finite',()=>{assert.ok(world.gatherables.every(n=>n.group.userData.dynamic));world.gatherables[0].group.visible=false;for(let i=0;i<10;i++)world.update(.05,i*.05,{x:0,z:28},.5);for(const a of world.animals)assert.ok(Number.isFinite(a.group.position.x)&&Number.isFinite(a.group.position.z));assert.ok(scene.children.filter(o=>o.isInstancedMesh).length<160,'Instanced world keeps draw calls bounded');});
