import test from 'node:test';
import assert from 'node:assert/strict';
import * as T from '../web/vendor/three.module.js';
import {ARCHETYPES,WEAPONS,SPELLS,ENEMY_DEFS,freshHero,stats,chooseArchetype,buyWeapon,equipWeapon,assignSpell,spendCast,spendAttack,tickHero,hurtHero,rewardKill,recover,drinkPotion,buySupply,validHero} from '../web/realm/rpg.js';
import {freshState,parseSave} from '../web/realm/economy.js';
import {createCombat,segmentBlocked,segmentEntry,sphereEntry,isSanctuary} from '../web/realm/combat.js';
import {weaponModel,adventurerModel,disposeModel} from '../web/realm/models.js';
import {projectedMaterial} from '../web/realm/materials.js';
import {createPostProcessing} from '../web/realm/postprocessing.js';
function setup(id='wizard'){const s=freshState();chooseArchetype(s,id);s.position={x:0,z:-60,yaw:0,pitch:0};const world={colliders:[]},events=[];const combat=createCombat({state:()=>s,world,emit:e=>events.push(e)});return{s,world,combat,events};}
function goblin(id,z){return{id,kind:'goblin',...ENEMY_DEFS.goblin,health:100,maxHealth:100,x:0,z,homeX:0,homeZ:z,heading:0,dead:false,freeze:100,slow:0,attackTime:10,flash:0};}

test('v3 save migration preserves the entire trading journey',()=>{const s=freshState();delete s.hero;s.coins=789;s.inventory.herbs=4;s.quest=2;const before=structuredClone(s),loaded=parseSave(JSON.stringify(s));assert.ok(loaded);assert.equal(loaded.hero.archetype,null);const copy={...loaded};delete copy.hero;assert.deepEqual(copy,before);});
test('all four archetypes have usable gear, distinct stats, and valid saves',()=>{for(const id of Object.keys(ARCHETYPES)){const s=freshState();assert.equal(chooseArchetype(s,id).ok,true);assert.equal(s.hero.health,stats(s.hero).health);assert.equal(s.hero.mana,stats(s.hero).mana);assert.ok(s.hero.weapons.includes('sword'));assert.ok(s.hero.weapons.includes(s.hero.equipped));assert.equal(validHero(s.hero),true);assert.deepEqual(parseSave(JSON.stringify(s)),s);}assert.equal(ARCHETYPES.wizard.spells.length,12);assert.ok(ARCHETYPES.ogre.health>ARCHETYPES.human.health);assert.ok(ARCHETYPES.elf.ranged>ARCHETYPES.human.ranged);});
test('character switching cannot repeatedly heal or duplicate starting equipment',()=>{const s=freshState();chooseArchetype(s,'human');s.hero.health=stats(s.hero).health/2;s.hero.mana=stats(s.hero).mana/2;chooseArchetype(s,'wizard');assert.equal(s.hero.health,stats(s.hero).health/2);chooseArchetype(s,'human');assert.equal(s.hero.health,stats(s.hero).health/2);assert.equal(s.hero.mana,stats(s.hero).mana/2);assert.equal(new Set(s.hero.weapons).size,s.hero.weapons.length);});
test('weapon purchases and equipment are atomic, including inherited property inputs',()=>{const s=freshState();s.coins=10000;for(const id of Object.keys(WEAPONS)){if(s.hero.weapons.includes(id))continue;const before=s.coins;assert.equal(buyWeapon(s,id).ok,true);assert.equal(s.coins,before-WEAPONS[id].price);const next=s.coins;assert.equal(buyWeapon(s,id).ok,false);assert.equal(s.coins,next);assert.equal(equipWeapon(s,id).ok,true);}for(const bad of ['constructor','toString','__proto__','missing']){const before=JSON.stringify(s);assert.equal(buyWeapon(s,bad).ok,false);assert.equal(buySupply(s,bad).ok,false);assert.equal(JSON.stringify(s),before);}const empty=freshState();assert.equal(equipWeapon(empty,'warhammer').ok,false);});
test('spells enforce knowledge, slot bounds, mana and cooldown without partial costs',()=>{const s=freshState();chooseArchetype(s,'human');for(const [slot,id]of [[-1,'heal'],[4,'heal'],[.5,'heal'],[0,'meteor']]){const before=JSON.stringify(s);assert.equal(assignSpell(s,slot,id).ok,false);assert.equal(JSON.stringify(s),before);}s.hero.mana=0;const before=JSON.stringify(s.hero);assert.equal(spendCast(s.hero,'fireball').ok,false);assert.equal(JSON.stringify(s.hero),before);s.hero.mana=85;assert.equal(spendCast(s.hero,'fireball').ok,true);assert.equal(s.hero.mana,85-SPELLS.fireball.cost);const after=JSON.stringify(s.hero);assert.equal(spendCast(s.hero,'fireball').ok,false);assert.equal(JSON.stringify(s.hero),after);});
test('all twelve wizard spells execute and spend their cost once',()=>{for(const id of Object.keys(SPELLS)){const {s,combat}=setup();s.hero.health-=10;assignSpell(s,0,id);const before=s.hero.mana;assert.equal(combat.cast(0).ok,true,id);assert.equal(s.hero.mana,before-SPELLS[id].cost,id);assert.equal(s.hero.cooldowns[id],SPELLS[id].cooldown,id);assert.equal(validHero(s.hero),true,id);}});
test('attack ammunition and mana cannot underflow, melee remains usable',()=>{const s=freshState();chooseArchetype(s,'elf');s.hero.arrows=0;const before=JSON.stringify(s.hero);assert.equal(spendAttack(s.hero).ok,false);assert.equal(JSON.stringify(s.hero),before);equipWeapon(s,'dagger');assert.equal(spendAttack(s.hero).ok,true);chooseArchetype(s,'wizard');s.hero.cooldowns.attack=0;s.hero.mana=0;assert.equal(spendAttack(s.hero).ok,false);equipWeapon(s,'sword');assert.equal(spendAttack(s.hero).ok,true);});
test('cooldowns and buffs use active time and survive save/reload',()=>{const {s,combat}=setup();s.hero.effects.ward=5;s.hero.shield=30;combat.cast(0);const time=combat.clock,before=JSON.stringify(s);combat.update(0);assert.equal(combat.clock,time);assert.equal(JSON.stringify(s),before);combat.update(.05);assert.ok(s.hero.cooldowns.fireball<SPELLS.fireball.cooldown);assert.ok(s.hero.effects.ward<5);const loaded=parseSave(JSON.stringify(s));assert.deepEqual(loaded.hero,s.hero);});
test('defensive spells absorb damage and guard reduces it',()=>{const h=freshHero();h.effects.ward=5;h.shield=50;assert.equal(hurtHero(h,20),0);assert.equal(h.health,125);assert.ok(h.shield<50);h.shield=0;const direct=hurtHero(h,10),guarded=hurtHero(h,10,true);assert.ok(guarded<direct);h.effects.grace=3;assert.equal(hurtHero(h,1000),0);});
test('nearest projectile collision wins even with a wall behind the target',()=>{for(const wall of [false,true]){const {s,world,combat}=setup('human');s.hero.equipped='crossbow';s.hero.bolts=3;const near=goblin('hostile-1',-62),far=goblin('hostile-0',-65);combat.enemies.splice(0,combat.enemies.length,far,near);if(wall)world.colliders.push({x1:-2,x2:2,z1:-64,z2:-63.9});assert.equal(combat.attack().ok,true);combat.update(.1);assert.equal(near.health,54);assert.equal(far.health,100);}});
test('projectiles cannot hit through a wall in front of the enemy',()=>{const {s,world,combat}=setup('human');s.hero.equipped='crossbow';const enemy=goblin('hostile-0',-63);combat.enemies.splice(0,combat.enemies.length,enemy);world.colliders.push({x1:-3,x2:3,z1:-61,z2:-60.9});combat.attack();combat.update(.1);assert.equal(enemy.health,100);});
test('aerial fireball explosions do not hit enemies far beneath them',()=>{const {s,combat,events}=setup();s.position.pitch=Math.PI/4;const enemy=goblin('hostile-0',-90);combat.enemies.splice(0,combat.enemies.length,enemy);combat.cast(0);for(let i=0;i<40;i++)combat.update(.05);assert.equal(enemy.health,100);assert.ok(events.some(e=>e.type==='burst'&&e.y>25));});
test('segment intersections return ordered entry points',()=>{const a={x:0,y:1,z:0},b={x:0,y:1,z:-10};assert.equal(segmentEntry(a,b,[{x1:-1,x2:1,z1:-5,z2:-4}]),.4);assert.ok(sphereEntry({x:0,y:1,z:-2},a,b,.5)<.4);assert.equal(segmentBlocked(a,b,[{x1:3,x2:4,z1:-5,z2:-4}]),false);});
test('blink follows collision paths and cannot cross a blocked river',()=>{const {s,combat}=setup();s.position={x:45,z:0,yaw:-Math.PI/2,pitch:0};assignSpell(s,0,'blink');combat.cast(0);assert.ok(s.position.x<50);assert.ok(s.position.x>45);});
test('sanctuaries prevent hostile damage and pursuit into town',()=>{const {s,combat}=setup();s.position={x:0,z:0,yaw:0,pitch:0};const enemy=goblin('hostile-0',-1);enemy.freeze=0;enemy.attackTime=0;combat.enemies.splice(0,combat.enemies.length,enemy);const hp=s.hero.health;for(let i=0;i<20;i++)combat.update(.05);assert.equal(s.hero.health,hp);assert.equal(isSanctuary(s.position),true);});
test('kill rewards pay once and large rewards cross multiple levels safely',()=>{const s=freshState();chooseArchetype(s,'wizard');const enemy={id:'hostile-0',coin:10,xp:900};const first=rewardKill(s,enemy);assert.ok(first.levels>1);const before=JSON.stringify(s);assert.equal(rewardKill(s,enemy).rewarded,false);assert.equal(JSON.stringify(s),before);assert.equal(validHero(s.hero),true);rewardKill(s,{id:'hostile-1',coin:10,xp:100000});assert.equal(s.hero.level,20);assert.equal(validHero(s.hero),true);});
test('recovery preserves trade progress, weapons and quests',()=>{const s=freshState();chooseArchetype(s,'ogre');s.coins=200;s.inventory.iron=6;s.quest=3;s.hero.health=0;const gear=[...s.hero.weapons];recover(s);assert.equal(s.coins,180);assert.equal(s.inventory.iron,6);assert.equal(s.quest,3);assert.deepEqual(s.hero.weapons,gear);assert.equal(s.hero.health,stats(s.hero).health);assert.equal(s.hero.effects.grace,8);assert.equal(isSanctuary(s.position),true);});
test('potions and supplies preserve upper bounds and charge exact prices',()=>{const s=freshState();chooseArchetype(s,'human');const full=s.hero.potions;assert.equal(drinkPotion(s).ok,false);assert.equal(s.hero.potions,full);s.hero.health=20;assert.equal(drinkPotion(s).ok,true);assert.equal(s.hero.health,85);const old=s.coins;assert.equal(buySupply(s,'arrows').ok,true);assert.equal(s.coins,old-12);assert.equal(s.hero.arrows,70);});
test('malformed RPG saves fail without accepting infinite or unowned gear',()=>{for(const mutate of [h=>h.mana=1e9,h=>h.equipped='unowned',h=>h.archetype='dragon',h=>h.cooldowns.fireball=-1,h=>h.effects.invalid=4,h=>h.slots=['meteor'],h=>h.weapons.push('constructor'),h=>h.health=-1]){const s=freshState();chooseArchetype(s,'wizard');mutate(s.hero);assert.equal(parseSave(JSON.stringify(s)),null);}});
test('all weapon and character models have finite 3D geometry',()=>{for(const id of Object.keys(WEAPONS)){const model=weaponModel(id),bounds=new T.Box3().setFromObject(model);assert.ok(!bounds.isEmpty());assert.ok(Number.isFinite(bounds.max.y));disposeModel(model);}for(const id of Object.keys(ARCHETYPES)){const model=adventurerModel(id),bounds=new T.Box3().setFromObject(model);assert.ok(bounds.max.y>1.8&&bounds.max.y<3,id);assert.ok(ARCHETYPES[id].eye<2.8);disposeModel(model);}});
test('textured material shader hooks and bundled rendering imports are valid',()=>{const texture=new T.Texture(),m=projectedMaterial(0xffffff,texture,.5),shader={uniforms:{},vertexShader:T.ShaderLib.standard.vertexShader,fragmentShader:T.ShaderLib.standard.fragmentShader};m.onBeforeCompile(shader);assert.equal(shader.uniforms.realmTileScale.value,.5);assert.ok(shader.vertexShader.includes('vRealmPosition=(modelMatrix*realmPos).xyz'));assert.ok(shader.fragmentShader.includes('texture2D(map,vRealmPosition.xz'));assert.equal(typeof createPostProcessing,'function');m.dispose();texture.dispose();});
