import * as T from '../vendor/three.module.js';
import {surfaceAt,RIVER} from './world.js';
import {TRAINING} from './combat.js';
import {BOSSES} from './bosses.js';
import {WEAPONS} from './rpg.js';
import {createSpellEffects} from './spell-effects.js';
import {weaponModel,enemyModel,mat,orb,rod,cube,disposeModel} from './models.js';
export function loadWorldTextures(renderer){const loader=new T.TextureLoader();const textures={};for(const [key,file]of Object.entries({grass:'forest-floor.png',stone:'cobblestone.png',wood:'oak-planks.png'})){const texture=loader.load(new URL('../assets/'+file,import.meta.url).href,undefined,undefined,()=>{});texture.colorSpace=T.SRGBColorSpace;texture.wrapS=texture.wrapT=T.RepeatWrapping;texture.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());textures[key]=texture;}return textures;}
export function createAtmosphere(scene){
 const uniforms={time:{value:0},day:{value:1},sun:{value:new T.Vector3(-.5,.65,.4).normalize()}};
 const sky=new T.Mesh(new T.SphereGeometry(460,36,20),new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms,vertexShader:'varying vec3 vSky; void main(){vSky=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`varying vec3 vSky; uniform float time; uniform float day; uniform vec3 sun;
float noise(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float smoothnoise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(noise(i),noise(i+vec2(1,0)),f.x),mix(noise(i+vec2(0,1)),noise(i+vec2(1,1)),f.x),f.y);}float fbm(vec2 p){return smoothnoise(p)*.55+smoothnoise(p*2.1)*.27+smoothnoise(p*4.2)*.13+smoothnoise(p*8.1)*.05;}
void main(){vec3 d=normalize(vSky);float h=max(d.y,0.);vec3 noon=mix(vec3(.72,.81,.76),vec3(.23,.46,.61),pow(h,.52));vec3 night=mix(vec3(.08,.13,.20),vec3(.012,.024,.065),pow(h,.5));vec3 color=mix(night,noon,day);float sd=max(dot(d,sun),0.);color+=vec3(1.,.8,.5)*(pow(sd,650.)*2.+pow(sd,16.)*.18)*day;vec2 uv=d.xz/max(.16,d.y)*1.9+vec2(time*.009,0.);float cloud=smoothstep(.5,.7,fbm(uv))*smoothstep(.03,.23,d.y);color=mix(color,mix(vec3(.16,.2,.28),vec3(.95,.93,.82),day),cloud*.78);float stars=step(.998,noise(floor(d.xz/max(.12,d.y)*300.)))*smoothstep(.1,.3,d.y);color+=stars*(1.-day)*.8;gl_FragColor=vec4(color,1.);}` }));sky.renderOrder=-10;sky.frustumCulled=false;scene.add(sky);
 // The river now rises from the frozen tarn and runs to the southern edge of the valley.
 const waterUniforms={time:{value:0},day:{value:1}},riverLength=300-RIVER.north;
 const water=new T.Mesh(new T.PlaneGeometry(11.7,riverLength,16,Math.round(riverLength/2.4)),new T.ShaderMaterial({transparent:true,depthWrite:false,uniforms:waterUniforms,vertexShader:`varying vec2 vUV; varying vec3 vWorld; uniform float time; void main(){vUV=uv; vec3 p=position;p.z+=sin(p.x*1.7+time*1.2)*.025+sin(p.y*.4+time)*.018;vec4 w=modelMatrix*vec4(p,1.);vWorld=w.xyz;gl_Position=projectionMatrix*viewMatrix*w;}`,fragmentShader:`varying vec2 vUV;varying vec3 vWorld;uniform float time;uniform float day;void main(){float wave=sin(vUV.x*140.+sin(vUV.y*70.+time)*2.+time*1.4)*sin(vUV.y*1300.-time*3.);float foam=smoothstep(.73,1.,wave)*.16;float edge=pow(abs(vUV.x-.5)*2.,18.);vec3 color=mix(vec3(.09,.27,.28),vec3(.27,.51,.48),vUV.x);color+=foam+edge*.12;vec3 view=normalize(cameraPosition-vWorld);float fresnel=pow(1.-abs(view.y),3.);color=mix(color,vec3(.57,.74,.78),fresnel*.65);gl_FragColor=vec4(color*(.25+day*.8),.94);}` }));water.rotation.x=-Math.PI/2;water.position.set(RIVER.x,.06,(RIVER.north+300)/2);scene.add(water);
 // Warm pools of light at doors make interiors legible without a light per prop.
 const lanterns=[];for(const [x,z]of [[-7,13],[7,13],[-11,-15],[11,-14],[-111,-93],[97,-120]]){const light=new T.PointLight(0xffc780,5,13,2);light.position.set(x,2.4,z);scene.add(light);lanterns.push(light);}
 return{update(time,day,position){uniforms.time.value=time;uniforms.day.value=day;waterUniforms.time.value=time;waterUniforms.day.value=day;sky.position.set(position.x,0,position.z);for(const l of lanterns)l.intensity=(1.5+(1-day)*6)*(1+Math.sin(time*4+l.position.x)*.05);},sky};
}
// First-person poses for the weapon hand: [position, rotation]. Strikes run windup → end, then recover to rest.
const REST=[[.36,-.4,-.66],[0,0,-.18]],GUARD=[[.04,-.3,-.56],[.05,0,1.42]],CAST=[[.3,-.32,-.72],[-.35,0,-.1]];
const POSES={
 slashR:{w:[[.62,-.2,-.58],[.1,.55,-1.25]],e:[[-.3,-.42,-.72],[-.45,-.45,1.2]],trail:'flat'},
 slashL:{w:[[-.3,-.24,-.6],[-.2,-.5,1.3]],e:[[.6,-.44,-.7],[-.5,.5,-1.25]],trail:'flat',flip:true},
 overhead:{w:[[.2,.12,-.42],[.8,0,-.25]],e:[[.06,-.64,-.82],[-1.5,0,-.1]],trail:'tall'},
 thrust:{w:[[.32,-.38,-.4],[-1.45,0,-.12]],e:[[.1,-.31,-1.1],[-1.53,0,-.02]]},
 rising:{w:[[-.22,-.64,-.52],[.35,-.35,1.35]],e:[[.52,.1,-.72],[-.35,.55,-1.2]],trail:'rise'},
 cleave:{w:[[.76,-.08,-.48],[0,.75,-1.5]],e:[[-.48,-.46,-.7],[-.55,-.65,1.45]],trail:'flat'},
 slam:{w:[[.16,.2,-.36],[1,0,-.2]],e:[[.02,-.72,-.86],[-1.62,0,-.05]],trail:'tall'},
 draw:{w:[[.26,-.36,-.46],[0,0,-.12]],e:[[.3,-.34,-.72],[-.08,0,-.14]]},
 recoil:{w:[[.36,-.38,-.6],[.22,0,-.18]],e:[[.36,-.4,-.7],[-.1,0,-.18]]}};
const HEAVY_POSE={rising:'rising',cleave:'cleave',concuss:'overhead',whirl:'cleave',lunge:'thrust',slam:'slam',flurry:'thrust',draw:'draw'};
const lerp3=(a,b,k,out)=>{for(let i=0;i<3;i++)out[i]=a[i]+(b[i]-a[i])*k;return out;};
const easeOut=k=>1-(1-k)**3,easeInOut=k=>k<.5?4*k*k*k:1-(-2*k+2)**3/2;
export function createCombatGraphics(scene,camera,state,settings){
 const group=new T.Group();scene.add(group);const enemyMeshes=new Map(),fx=createSpellEffects(scene,settings);let heldId='',heldClass='',heldModel=null,recoil=0,castFlash=0,hurt=0,wardHit=0,ambient=0,anim=null,trailLife=0,beamTimer=0,portalTimer=0;
 const hands=new T.Group();camera.add(hands);scene.add(camera);hands.position.set(...REST[0]);const offhand=new T.Group();offhand.position.set(-.32,-.35,-.55);camera.add(offhand);const glow=orb(offhand,mat(0xb9a2ff,.1,2),0,.11,-.1,.035),handLight=new T.PointLight(0xc4a2ff,0,3);offhand.add(handLight);
 const pose={p:[...REST[0]],r:[...REST[1]]},tmpP=[0,0,0],tmpR=[0,0,0];
 const castSeal=new T.Group();offhand.add(castSeal);castSeal.position.set(0,.13,-.14);const sealMaterial=new T.MeshBasicMaterial({color:0xcab7ff,transparent:true,opacity:.6,side:T.DoubleSide,blending:T.AdditiveBlending,depthWrite:false});for(const r of [.11,.145])castSeal.add(new T.Mesh(new T.TorusGeometry(r,.004,4,40),sealMaterial));for(let i=0;i<6;i++){const a=i/6*Math.PI*2,m=new T.Mesh(new T.OctahedronGeometry(.012),sealMaterial);m.position.set(Math.cos(a)*.13,Math.sin(a)*.13,0);castSeal.add(m);}
 // A single reusable ribbon traces each melee swing in camera space.
 const trailMaterial=new T.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:0,side:T.DoubleSide,blending:T.AdditiveBlending,depthWrite:false,toneMapped:false}),trail=new T.Mesh(new T.RingGeometry(.34,.66,40,1,-.15,Math.PI+.3),trailMaterial);trail.visible=false;trail.renderOrder=20;camera.add(trail);
 const tipGlow=new T.Mesh(new T.SphereGeometry(1,10,8),new T.MeshBasicMaterial({color:0xfff2c0,transparent:true,opacity:0,blending:T.AdditiveBlending,depthWrite:false,toneMapped:false}));tipGlow.scale.setScalar(.035);tipGlow.visible=false;hands.add(tipGlow);
 const wardMaterial=new T.ShaderMaterial({transparent:true,side:T.DoubleSide,depthWrite:false,blending:T.AdditiveBlending,uniforms:{time:{value:0},impact:{value:0}},vertexShader:`varying vec3 vNormal;varying vec3 vView;varying vec2 vUV;void main(){vec4 v=modelViewMatrix*vec4(position,1.);vNormal=normalize(normalMatrix*normal);vView=normalize(-v.xyz);vUV=uv;gl_Position=projectionMatrix*v;}`,fragmentShader:`varying vec3 vNormal;varying vec3 vView;varying vec2 vUV;uniform float time;uniform float impact;void main(){float rim=pow(1.-abs(dot(normalize(vNormal),normalize(vView))),2.);vec2 grid=vUV*vec2(24.,12.);float cells=pow(abs(sin(grid.x*3.14159)*sin(grid.y*3.14159)),14.);float sweep=pow(.5+.5*sin(vUV.y*30.-time*3.),12.);float a=.025+rim*.13+cells*.08+sweep*.025+impact*.13;gl_FragColor=vec4(vec3(.43,.65,1.5),a);}`});const ward=new T.Mesh(new T.SphereGeometry(1.25,36,24),wardMaterial);scene.add(ward);
 const wisp=new T.Group();orb(wisp,mat(0x9cf4df,0,3),0,0,0,.11);for(let i=0;i<2;i++){const halo=new T.Mesh(new T.TorusGeometry(.2+i*.07,.012,5,32),new T.MeshBasicMaterial({color:0x9cf8e6,transparent:true,opacity:.6,blending:T.AdditiveBlending,depthWrite:false}));halo.rotation.x=i*Math.PI/2;wisp.add(halo);}scene.add(wisp);
 const aim=new T.Mesh(new T.RingGeometry(.96,1,64),new T.MeshBasicMaterial({color:0xaddfff,transparent:true,opacity:.38,side:T.DoubleSide,depthWrite:false}));aim.rotation.x=-Math.PI/2;scene.add(aim);
 // Sunlance: a white-hot core inside a golden sheath, from the off-hand to where the beam lands.
 const beam=new T.Group(),beamGeo=new T.CylinderGeometry(1,1,1,10,1,true),beamCore=new T.Mesh(beamGeo,new T.MeshBasicMaterial({color:0xfff8dc,transparent:true,opacity:.9,blending:T.AdditiveBlending,depthWrite:false,toneMapped:false})),beamGlow=new T.Mesh(beamGeo,new T.MeshBasicMaterial({color:0xffd66b,transparent:true,opacity:.32,blending:T.AdditiveBlending,depthWrite:false,toneMapped:false}));beam.add(beamCore,beamGlow);beam.visible=false;scene.add(beam);
 const beamFrom=new T.Vector3(),beamTo=new T.Vector3(),beamDir=new T.Vector3(),up=new T.Vector3(0,1,0);
 // The Old Stones rift: a swirling violet gate that opens once the three sigils are won.
 const portalUniforms={time:{value:0}},portal=new T.Group(),hollow=BOSSES.hollow;portal.position.set(hollow.x,surfaceAt(hollow.x,hollow.z)+3.3,hollow.z);portal.visible=false;scene.add(portal);
 portal.add(new T.Mesh(new T.CircleGeometry(2.7,56),new T.ShaderMaterial({transparent:true,depthWrite:false,side:T.DoubleSide,blending:T.AdditiveBlending,uniforms:portalUniforms,vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`varying vec2 vUv;uniform float time;void main(){vec2 p=vUv-.5;float r=length(p)*2.;float a=atan(p.y,p.x);float swirl=.5+.5*sin(a*5.+r*13.-time*3.2);float veins=pow(.5+.5*sin(a*11.-r*20.+time*2.),6.);float edge=smoothstep(1.,.78,r);float core=smoothstep(.55,0.,r);vec3 col=mix(vec3(.38,.2,.85),vec3(.96,.82,1.),swirl*.55+core*.55)+veins*vec3(.5,.35,.9);gl_FragColor=vec4(col*(.55+swirl*.8),edge*(.3+swirl*.45+core*.25));}`})));
 const portalRing=new T.Mesh(new T.TorusGeometry(2.75,.07,8,64),new T.MeshBasicMaterial({color:0xd7bcff,transparent:true,opacity:.85,blending:T.AdditiveBlending,depthWrite:false,toneMapped:false}));portal.add(portalRing);
 const statusCrystal=new T.OctahedronGeometry(1),statusSphere=new T.SphereGeometry(1,10,8),statusRing=new T.TorusGeometry(.52,.05,5,20),starGeo=new T.OctahedronGeometry(1,0);
 const frostMat=new T.MeshBasicMaterial({color:0x9adcff,transparent:true,opacity:.3,depthWrite:false}),rootMat=new T.MeshStandardMaterial({color:0x638945,roughness:.9}),starMat=new T.MeshBasicMaterial({color:0xffe27a,transparent:true,opacity:.95,blending:T.AdditiveBlending,depthWrite:false,toneMapped:false});
 // A safe practice space beside the southern Eldermere road.
 const practice=new T.Group();practice.position.set(TRAINING.x,surfaceAt(TRAINING.x,TRAINING.z)+.035,TRAINING.z);scene.add(practice);
 const ring=new T.Mesh(new T.TorusGeometry(4.7,.045,5,64),new T.MeshStandardMaterial({color:0xa3c6d0,emissive:0x74bfd0,emissiveIntensity:.35}));ring.rotation.x=-Math.PI/2;practice.add(ring);for(let i=0;i<12;i++){const a=i/12*Math.PI*2;const stone=cube(practice,0x748080,Math.cos(a)*4.7,.1,Math.sin(a)*4.7,.3,.2,.3);stone.rotation.y=a;}
 const focus=new T.Group();focus.position.set(TRAINING.focus.x,surfaceAt(TRAINING.focus.x,TRAINING.focus.z),TRAINING.focus.z);scene.add(focus);rod(focus,0x667977,0,.38,0,.35,.76);const focusGem=new T.Mesh(new T.OctahedronGeometry(.25),mat(0xa6dfff,.25,1.8));focusGem.position.y=1.12;focus.add(focusGem);
 const cv=document.createElement('canvas');cv.width=768;cv.height=256;const ctx=cv.getContext('2d');ctx.fillStyle='#172d38';ctx.fillRect(0,0,768,256);ctx.strokeStyle='#a2c8d6';ctx.lineWidth=5;ctx.strokeRect(8,8,752,240);ctx.textAlign='center';ctx.fillStyle='#e2e6d5';ctx.font='42px Georgia';ctx.fillText('ARCANE PRACTICE',384,79);ctx.font='28px sans-serif';ctx.fillText('Strike the targets · try spell combinations',384,134);ctx.fillStyle='#a6dfff';ctx.fillText('E at the blue stone: restore mana & spells',384,190);const tex=new T.CanvasTexture(cv);tex.colorSpace=T.SRGBColorSpace;const sign=new T.Mesh(new T.PlaneGeometry(3.1,1.03),new T.MeshBasicMaterial({map:tex,side:T.DoubleSide}));sign.position.set(TRAINING.x,surfaceAt(TRAINING.x,TRAINING.z)+2.5,TRAINING.z-4.5);scene.add(sign);
 const weaponKind=()=>WEAPONS[state().hero.equipped]?.kind||'melee';
 function startSwing(e){const w=WEAPONS[e.weapon]||WEAPONS[state().hero.equipped];if(!w)return;
  if(w.kind!=='melee'&&!(e.heavy&&e.move==='draw')){recoil=1;anim={name:w.kind==='magic'?'thrust':'recoil',t:0,dur:.24,from:[[...pose.p],[...pose.r]],heavy:false};return;}
  let name=e.heavy?HEAVY_POSE[e.move]||'overhead':['spear','dagger'].includes(e.weapon)?'thrust':['slashR','slashL','overhead'][e.combo||0]||'slashR';
  const dur=e.heavy?(e.move==='flurry'?.42:e.move==='whirl'?.52:.46):Math.max(.24,Math.min(.4,w.cooldown*.72));
  anim={name,t:0,dur,from:[[...pose.p],[...pose.r]],heavy:!!e.heavy,move:e.move,charged:!!e.heavy};
  const spec=POSES[name];if(spec?.trail){trail.visible=true;trailLife=1;trailMaterial.color.setHex(w.color).multiplyScalar(e.heavy?1.6:1.15);trail.position.set(0,-.12,-.62);trail.scale.set(spec.flip?-1:1,1,1).multiplyScalar(e.heavy?1.25:1);if(spec.trail==='tall')trail.rotation.set(0,Math.PI/2,0);else if(spec.trail==='rise')trail.rotation.set(-1.1,0,.6);else trail.rotation.set(-1.25,0,0);}}
 function emit(e){fx.emit(e);if(e.type==='swing')startSwing(e);if(e.type==='cast'){castFlash=1;glow.material=mat(e.color,0,2);handLight.color.setHex(e.color);sealMaterial.color.setHex(e.color);}if(e.type==='hurt'&&e.amount>0&&!e.dot)hurt=.5;if(e.type==='guard'||e.type==='parry')wardHit=1;if(e.type==='clear'){recoil=castFlash=hurt=wardHit=0;anim=null;trailLife=0;trail.visible=false;beam.visible=false;}}
 function refreshWeapon(){const h=state().hero;if(heldId===h.equipped&&heldClass===h.archetype)return;heldId=h.equipped;heldClass=h.archetype;if(heldModel)disposeModel(heldModel);for(const child of [...hands.children])if(child!==tipGlow)child.removeFromParent();heldModel=weaponModel(h.equipped);heldModel.scale.setScalar(h.equipped==='crossbow'?.7:.48);const box=new T.Box3().setFromObject(heldModel);tipGlow.position.set(0,Math.max(.15,box.max.y*.94),0);hands.add(heldModel);const skin=h.archetype==='ogre'?0x8b9d64:0xc59e7a;orb(heldModel,skin,0,.05,.04,.075,.1,.055);rod(heldModel,h.archetype==='wizard'?0x564378:0x484b40,0,-.1,.05,.067,.18);heldModel.traverse(o=>{if(o.isMesh)o.castShadow=false;});offhand.children.filter(c=>c.userData.hand).forEach(c=>c.removeFromParent());const hand=orb(offhand,skin,0,0,0,.057,.09,.045);hand.userData.hand=true;}
 // Pose the weapon hand: scripted swings first, then charge windups, guard, and rest (damped).
 function animateHands(tick,time,combat,moving){const blocking=combat.blocking,kind=weaponKind(),h=state().hero,w=WEAPONS[h.equipped];let target=REST;
  if(anim){anim.t+=tick/anim.dur;const spec=POSES[anim.name]||POSES.slashR,k=Math.min(1,anim.t),antic=anim.charged?.08:.18;
   if(k<antic){const q=easeInOut(k/antic);lerp3(anim.from[0],spec.w[0],q,pose.p);lerp3(anim.from[1],spec.w[1],q,pose.r);}
   else if(k<.55){const q=easeOut((k-antic)/(.55-antic));lerp3(spec.w[0],spec.e[0],q,pose.p);lerp3(spec.w[1],spec.e[1],q,pose.r);if(anim.move==='flurry')pose.p[2]-=Math.sin(q*Math.PI*3)*.14;}
   else{const q=easeInOut((k-.55)/.45);lerp3(spec.e[0],REST[0],q,pose.p);lerp3(spec.e[1],REST[1],q,pose.r);}
   if(anim.t>=1)anim=null;}
  else{if(combat.charging&&w?.heavy){const spec=POSES[HEAVY_POSE[w.heavy.move]]||POSES.overhead,k=easeOut(Math.min(1,(combat.charge||0)/.45));lerp3(REST[0],spec.w[0],k,tmpP);lerp3(REST[1],spec.w[1],k,tmpR);if(w.kind==='ranged')tmpP[2]+=.14*k;if(combat.chargeReady&&!settings.reducedMotion){const s=combat.charge>=1?.009:.004;tmpP[0]+=Math.sin(time*47)*s;tmpP[1]+=Math.cos(time*53)*s;}target=[tmpP,tmpR];}
   else if(blocking)target=kind==='melee'?GUARD:[[.18,-.34,-.58],[0,0,.7]];
   else if(castFlash>.2)target=CAST;
   const k=1-Math.exp(-tick*16);lerp3(pose.p,target[0],k,pose.p);lerp3(pose.r,target[1],k,pose.r);}
  const bob=!settings.reducedMotion&&moving?Math.sin(time*8)*.008:0,kick=Math.sin(recoil*Math.PI)*.06;
  hands.position.set(pose.p[0],pose.p[1]+bob,pose.p[2]+kick);hands.rotation.set(pose.r[0]-kick*2,pose.r[1],pose.r[2]);
  trailLife=Math.max(0,trailLife-tick*4.6);trail.visible=trailLife>0;trailMaterial.opacity=trailLife*trailLife*.55;
  const riposte=(combat.riposte||0)>0&&kind==='melee';tipGlow.visible=riposte;if(riposte){tipGlow.material.opacity=.55+Math.sin(time*12)*.35;tipGlow.scale.setScalar(.03+Math.sin(time*9)*.008);}}
 function updateBeam(combat,tick,time){const ch=combat.channel;if(!ch?.end||!Number.isFinite(ch.end.x)){beam.visible=false;return;}offhand.getWorldPosition(beamFrom);beamFrom.y+=.08;beamTo.set(ch.end.x,ch.end.y,ch.end.z);beamDir.subVectors(beamTo,beamFrom);const length=beamDir.length();if(length<.05){beam.visible=false;return;}beam.visible=true;beam.position.copy(beamFrom).addScaledVector(beamDir,.5);beam.quaternion.setFromUnitVectors(up,beamDir.normalize());const flick=1+Math.sin(time*31)*.12;beamCore.scale.set(.035*flick,length,.035*flick);beamGlow.scale.set(.14*flick,length,.14*flick);beamGlow.material.opacity=.26+Math.sin(time*17)*.08;
  beamTimer+=tick;if(beamTimer>.035){beamTimer=0;const color=ch.targetId?0xfff0b0:0xffd66b;for(let i=0;i<(settings.quality==='low'?1:3);i++)fx.particle(beamTo,color,{vx:(Math.random()-.5)*3,vy:1+Math.random()*2,vz:(Math.random()-.5)*3,life:.35+Math.random()*.3,size:.18,gravity:3});}}
 function updatePortal(combat,tick,time){const king=(combat.bosses||combat.enemies||[]).find(e=>e.boss==='hollow');portal.visible=!!king&&!king.dormant&&!king.dead;if(!portal.visible)return;portalUniforms.time.value=time;portal.lookAt(camera.position.x,portal.position.y,camera.position.z);portalRing.rotation.z=time*.4;portal.scale.setScalar(1+Math.sin(time*1.7)*.03);portalTimer+=tick;if(portalTimer>.08){portalTimer=0;const a=Math.random()*Math.PI*2;fx.particle({x:portal.position.x+Math.cos(a)*2.6,y:portal.position.y+Math.sin(a)*2.6,z:portal.position.z},0xcaa8ff,{vx:-Math.cos(a)*1.2,vy:-Math.sin(a)*1.2,life:1.2,size:.22,drag:.4});}}
 function syncEnemies(combat,time,paused){const enemies=combat.enemies,player=combat.player||state().position,ids=new Set(enemies.map(e=>e.id));
  for(const [id,g]of enemyMeshes)if(!ids.has(id)){for(const key of ['ice','roots','flash','stars'])g.userData[key]?.removeFromParent();g.userData.flash.material.dispose();disposeModel(g);enemyMeshes.delete(id);}
  for(const e of enemies){let g=enemyMeshes.get(e.id);const size=e.size||g?.userData.size||{r:.7,y:1.1},k=Math.max(1,size.r/.7);
   if(!g){g=enemyModel(e.kind);group.add(g);const status=new T.Group();g.add(status);for(let i=0;i<5;i++){const a=i*2.4,m=new T.Mesh(statusCrystal,frostMat);m.position.set(Math.cos(a)*.45,.25,Math.sin(a)*.45);m.scale.set(.1,.5,.1);status.add(m);}status.scale.setScalar(k);const roots=new T.Mesh(statusRing,rootMat);roots.rotation.x=Math.PI/2;roots.position.y=.35;roots.scale.setScalar(k);g.add(roots);const flash=new T.Mesh(statusSphere,new T.MeshBasicMaterial({color:0xffdfb5,transparent:true,opacity:0,depthWrite:false,blending:T.AdditiveBlending}));flash.position.y=e.boss?size.y:1.1;flash.scale.set(.52*k,e.boss?size.y*.9:.85,.5*k);g.add(flash);const stars=new T.Group();stars.position.y=size.y*1.75+.35;for(let i=0;i<5;i++){const s=new T.Mesh(starGeo,starMat);s.scale.set(.07*k,.1*k,.07*k);s.position.set(Math.cos(i/5*Math.PI*2)*.45*k,0,Math.sin(i/5*Math.PI*2)*.45*k);stars.add(s);}stars.visible=false;g.add(stars);Object.assign(g.userData,{ice:status,roots,flash,stars});enemyMeshes.set(e.id,g);}
   const far=Math.hypot(e.x-player.x,e.z-player.z)>(e.boss?230:150);g.visible=!e.dead&&!e.dormant&&!far;if(!g.visible)continue;
   const u=g.userData;u.ice.visible=e.chill>0||e.iceLock>0;u.roots.visible=e.bind>0;u.flash.material.opacity=(e.flash||0)*2;u.stars.visible=(e.stagger||0)>0;if(u.stars.visible){u.stars.rotation.y=time*4;u.stars.position.y=size.y*1.75+.35+Math.sin(time*6)*.05;}
   const moved=!paused&&Math.hypot(g.position.x-e.x,g.position.z-e.z)>.002,atk=e.attack,prog=atk?.total?Math.min(1,1-atk.remaining/atk.total):0,wind=e.windup>0&&e.windupTotal?1-e.windup/e.windupTotal:0;
   for(let i=0;i<(u.legs||[]).length;i++)u.legs[i].rotation.x=moved?Math.sin(time*9+i*Math.PI)*.32:0;
   for(let i=0;i<(u.arms||[]).length;i++){const arm=u.arms[i];arm.rotation.x=e.windup>0?-.6-Math.sin(wind*Math.PI/2)*1.1:atk?-.4-Math.sin(prog*Math.PI/2)*(e.kind==='colossus'?1.5:1.2):moved?Math.sin(time*9+i*Math.PI)*.2:Math.sin(time*1.3+i)*.06;}
   if(u.neck){u.neck.rotation.y=Math.sin(time*.6)*.14;u.neck.rotation.x=atk?-.3*Math.sin(prog*Math.PI):Math.sin(time*.8)*.05;}
   if(u.jaw)u.jaw.rotation.x=atk?.12+.5*Math.sin(Math.min(1,prog*1.2)*Math.PI/2):.05+Math.sin(time*1.3)*.03;
   if(u.wings)for(const w of u.wings)w.rotation.z=w.userData.side*(.35+Math.sin(time*(atk?4:1.4))*(atk?.28:.12)+prog*.3);
   if(u.tail)u.tail.rotation.y=Math.sin(time*1.1)*.28;
   if(u.orbs){u.orbs.rotation.y=time*(e.kind==='witch'?1.2:.9);u.orbs.position.y=(e.kind==='witch'?2.6:2.3)+Math.sin(time*2)*.12;}
   if(u.core)u.core.scale.setScalar(.5*(1+Math.sin(time*3)*.08+prog*.35));
   g.position.set(e.x,surfaceAt(e.x,e.z),e.z);g.rotation.y=e.heading;if(e.kind==='wraith')g.position.y+=.14+Math.sin(e.x+time*2)*.12;if(e.kind==='witch')g.position.y+=.55+Math.sin(time*1.4)*.18;if(e.stagger>0&&e.boss)g.rotation.z=Math.sin(time*7)*.04;else g.rotation.z=0;}}
 function update(dt,time,combat,playing,paused,moving){const h=state().hero,p=state().position,tick=paused?0:dt;refreshWeapon();hands.visible=offhand.visible=playing&&!paused;recoil=Math.max(0,recoil-tick*4);castFlash=Math.max(0,castFlash-tick*2.2);hurt=Math.max(0,hurt-tick);wardHit=Math.max(0,wardHit-tick*3);
  animateHands(tick,time,combat,moving);offhand.rotation.z=castFlash*.5;offhand.position.z=-.55+(combat.channel?-.08:0);glow.scale.setScalar(1+castFlash*4+(combat.channel?2.5:0));handLight.intensity=castFlash*3+(combat.channel?2:0);castSeal.visible=castFlash>0||!!combat.channel;castSeal.scale.setScalar(.6+Math.max(castFlash,combat.channel?.7:0));castSeal.rotation.z=time*(combat.channel?5:2);sealMaterial.opacity=Math.max(castFlash*.8,combat.channel?.7:0);
  ward.visible=playing&&h.effects.ward>0&&h.shield>0;ward.position.set(p.x,surfaceAt(p.x,p.z)+1,p.z);wardMaterial.uniforms.time.value=time;wardMaterial.uniforms.impact.value=wardHit;
  wisp.visible=playing&&h.effects.wisp>0;wisp.position.set(p.x+Math.cos(time*1.4),surfaceAt(p.x,p.z)+2.2+Math.sin(time*2)*.2,p.z+Math.sin(time*1.4));wisp.rotation.y=time;wisp.rotation.z=Math.sin(time)*.2;
  const target=playing&&!paused?combat.aim():null;aim.visible=!!target;if(target){aim.position.set(target.x,target.y,target.z);aim.scale.setScalar(target.radius);aim.material.color.setHex(target.color);aim.material.opacity=.22+Math.sin(time*3)*.08;}
  if(playing&&!paused)updateBeam(combat,tick,time);else beam.visible=false;updatePortal(combat,tick,time);
  focusGem.rotation.y=time*.5;focusGem.position.y=1.12+Math.sin(time*2)*.05;ambient+=tick;if(ambient>.1){ambient=0;if(wisp.visible)fx.particle(wisp.position,0x98f8e3,{life:.9,size:.17,vy:.3});if(h.effects.haste>0&&moving)for(let i=0;i<4;i++)fx.particle({x:p.x+(Math.random()-.5)*1.5,y:surfaceAt(p.x,p.z)+Math.random(),z:p.z+(Math.random()-.5)*1.5},0xc3ebbf,{life:.5,size:.16,vy:.7});}
  const overlay=document.querySelector('#damage-overlay');if(overlay)overlay.style.opacity=String(hurt*.7);syncEnemies(combat,time,paused);fx.update(tick,combat,playing);
 }
 return{emit,update,refreshWeapon,enemyMeshes,fx};
}
