import {ARCHETYPES,WEAPONS,SPELLS,DEALERS,BREWS,stats,nextLevelXP,spellRank} from './rpg.js';
import {BOSSES,BOSS_KEYS} from './bosses.js';
import {heroPreview} from './models.js';
const colorHex=c=>'#'+(c>>>0).toString(16).padStart(6,'0').slice(-6);
const ROMAN=['I','II','III','IV','V'];
export const SIGIL_GLYPHS={frost:'❄',mire:'✿',cinder:'✹',hollow:'♛'};
export const ELEMENTS={ice:'Ice',fire:'Fire',storm:'Storm',arcane:'Arcane',nature:'Nature',radiant:'Radiant',shadow:'Shadow',earth:'Earth'};
const DEALER_NAMES={rowan:'Rowan in Eldermere',gareth:'Gareth in Ironhold',halvard:'Halvard in Frostwatch'};
const HEAVY={rising:'rising slash',flurry:w=>'flurry of '+(w.heavy.hits||3)+' stabs',cleave:'sweeping cleave',concuss:'concussive blow · stuns',whirl:'whirlwind · strikes all around',lunge:w=>'lunge '+(w.heavy.lunge||4)+' m',slam:w=>'ground slam · '+(w.heavy.radius||4)+' m',draw:w=>'full draw · pierces '+(w.heavy.pierce||0)+' foes'};
// "Hold: rising slash" style line for weapons with a charged attack; '' otherwise.
export function heavyText(w){const hv=w?.heavy;if(!hv)return '';const d=HEAVY[hv.move];let t=typeof d==='function'?d(w):d||hv.move||'heavy blow';if(hv.fire)t+=' · sets the ground ablaze';if(hv.wave==='ice')t+=' · looses a frost wave';if(hv.wave==='rift')t+=' · looses a rift crescent';return 'Hold: '+t;}
const tabs=`<nav class="rpg-tabs" aria-label="Character menus"><button data-action="rpg-tab" data-view="hero">Character</button><button data-action="rpg-tab" data-view="armory">Equipment</button><button data-action="rpg-tab" data-view="spellbook">Spellbook</button></nav>`;
const controlsHelp=`<div class="controls-help"><kbd>Click / Space</kbd><span>Attack · keep striking for a three-hit combo with a heavy finisher</span><kbd>Hold attack</kbd><span>Charge a heavy blow · release when the ring fills</span><kbd>R / right mouse</kbd><span>Guard · raise it just before a hit to <b>parry</b> and open a riposte</span><kbd>V / Ctrl</kbd><span>Dodge roll · slip through attacks, even unblockable ones</span><kbd>1–4 · Q · Z</kbd><span>Cast spells · Q repeats the selected spell · hold Sunlance to channel</span><kbd>F · wheel</kbd><span>Healing draught · cycle weapons</span><kbd>G</kbd><span>Mana draught · restores ${BREWS.mana.restore} mana · tonics are drunk from the satchel (I)</span></div>`;
export function createRPGPanels(){let selected='wizard',disposePreview=null;
 return{cleanup(){disposePreview?.();disposePreview=null;},select(id){if(ARCHETYPES[id])selected=id;},
 render(name,s,merchant){const h=s.hero,a=stats(h),legends=Array.isArray(h.bosses)?h.bosses:[],points=Number.isFinite(h.points)?h.points:0;if(name==='characters'){
  const chosen=ARCHETYPES[selected];return{title:'Choose your adventurer',kicker:'FOUR PATHS INTO ELDERWOOD',html:`<div class="character-choice"><div class="character-list">${Object.entries(ARCHETYPES).map(([id,c],i)=>`<button class="character-option ${id===selected?'selected':''}" style="--hero-color:${c.color}" data-action="rpg-preview" data-id="${id}" aria-pressed="${id===selected}"><span class="character-number">0${i+1}</span><span><strong>${c.name}</strong><small>${c.title}</small></span><span>↗</span></button>`).join('')}</div><div class="character-display"><canvas id="hero-preview" width="320" height="350" aria-label="3D preview of the selected ${chosen.name}"></canvas><span class="character-caption">${chosen.title}</span></div></div><p class="dialogue character-description">${chosen.description}</p><div class="character-stats"><span><b>${chosen.health}</b> Health</span><span><b>${chosen.mana}</b> Mana</span><span><b>${chosen.spells.length}</b> Spells</span></div><p class="merchant-note">Starts with ${chosen.gear.map(id=>WEAPONS[id].name).join(' and ')}. Every character can wield all weapon families, and any hero may claim the legendary arms of a fallen legend.</p><button class="primary" data-action="rpg-choose" data-id="${selected}">${h.archetype?'Become':'Play as'} ${chosen.name} <span>↗</span></button><p class="merchant-note">${h.archetype?'Changing character preserves your level, skill points, belongings, and current health and mana proportions.':'Your existing trading progress is preserved. You can change character later inside a settlement.'}</p>`};
 }
 if(name==='hero'){const n=legends.length;return{title:ARCHETYPES[h.archetype]?.title||'Your adventurer',kicker:'LEVEL '+h.level+' · '+(ARCHETYPES[h.archetype]?.name||'HUMAN').toUpperCase(),html:tabs+`<div class="hero-summary"><div><p class="dialogue">${ARCHETYPES[h.archetype]?.description||'Choose the path you will follow.'}</p><div class="character-stats"><span><b>${Math.ceil(h.health)} / ${a.health}</b> Health</span><span><b>${Math.floor(h.mana)} / ${a.mana}</b> Mana</span><span><b>${points}</b> Skill points</span><span><b>${h.kills}</b> Foes defeated</span></div><p class="merchant-note">${h.xp} / ${nextLevelXP(h)} XP toward the next level · Level cap 20 · each level grants a skill point</p><div class="xp-track"><i style="width:${Math.min(100,h.xp/nextLevelXP(h)*100)}%"></i></div></div><canvas id="hero-preview" width="320" height="350" aria-label="Your current character in 3D"></canvas></div>
<h3 class="journal-heading">Legends slain · ${n} / ${BOSS_KEYS.length}</h3><div class="sigil-row">${BOSS_KEYS.map(k=>{const b=BOSSES[k],won=legends.includes(k);return`<span class="sigil ${won?'won':''}" style="--sigil:${colorHex(b.color)}" title="${b.sigil}"><i>${SIGIL_GLYPHS[k]||'✦'}</i><small>${won?b.sigil:b.name+' · unclaimed'}</small></span>`;}).join('')}</div><p class="hero-boons">${n?`Legend boons: <b>+${n*12} health</b> · <b>+${n*10} mana</b> · <b>+${n*3}% power</b>`:'Each fallen legend grants a sigil, its legendary weapon, skill points, and a lasting boon of +12 health and +10 mana.'}</p>
<div class="brew-pouch">${Object.entries(BREWS).map(([id,b])=>{const n=h.brews?.[id]||0,t=h.effects?.[id]||0;return`<span class="brew-${id} ${n?'':'empty'}"><b>${n}</b>${b.name}${t>0?`<small>active · ${Math.ceil(t)}s</small>`:''}</span>`;}).join('')}</div><p class="merchant-note">Herbalists brew these from satchel goods: Elin in Eldermere, Brenna in Frostwatch. Press G for a mana draught; drink tonics from your satchel.</p>
<div class="dialogue-actions"><button data-action="rpg-tab" data-view="characters">Change character in town</button><button data-action="rpg-potion" ${h.potions<1||h.health>=a.health?'disabled':''}>Drink healing draught · ${h.potions} left</button><button data-action="rpg-brew" data-id="mana" ${!(h.brews?.mana>0)||h.mana>=a.mana?'disabled':''}>Drink mana draught · ${h.brews?.mana||0} left</button>${points>0?`<button data-action="rpg-tab" data-view="spellbook">Study spells · ${points} point${points===1?'':'s'}</button>`:''}</div>${controlsHelp}<p class="merchant-note">Villagers and peaceful wildlife are not combat targets. Staggered foes take 30% more damage, and a riposte after a parry or perfect dodge strikes for 80% more.</p>`};}
 if(name==='armory'){const dealer=!!merchant&&DEALERS.includes(merchant.id),total=Object.keys(WEAPONS).length;return{title:dealer?'Weapons & provisions':'Your armory',kicker:dealer?'FORGED FOR THE OPEN ROAD':'EQUIPMENT · '+h.weapons.length+' / '+total,html:tabs+`<p class="merchant-note">${dealer?'Purchase and equip weapons here. Legendary arms are never for sale.':'Equip anything you own. '+DEALERS.map(d=>DEALER_NAMES[d]||d).join(', ').replace(/, ([^,]*)$/,' and $1')+' sell every common weapon and combat supplies.'} Hold attack with most weapons to charge a heavy blow. <b class="trade-balance">${s.coins} coin</b></p><div class="weapon-grid">${Object.entries(WEAPONS).map(([id,w])=>{const owned=h.weapons.includes(id),equipped=h.equipped===id,legend=w.legendary?BOSSES[w.legendary]:null,heavy=heavyText(w);
   const btn=owned?`<button data-action="rpg-equip" data-id="${id}" ${equipped?'disabled':''}>${equipped?'Equipped':'Equip'}</button>`:legend?`<button disabled>LEGENDARY · Defeat ${legend.name}</button>`:`<button data-action="rpg-buy" data-id="${id}" ${!dealer||s.coins<w.price?'disabled':''}>${dealer?'Buy · '+w.price+' coin':'Available from a merchant'}</button>`;
   return`<article class="weapon-card ${equipped?'equipped':''} ${legend?'legendary':''}"${legend?` style="--legend-color:${colorHex(legend.color)}"`:''}><div class="weapon-card-top"><span>${legend?'Legendary · ':''}${w.family}</span><small>${equipped?'EQUIPPED':owned?'OWNED':legend?'LEGENDARY':w.price+' COIN'}</small></div><h3>${w.name}</h3><p>${w.description}</p>${legend?`<p class="legend-source">${owned?'Claimed from':'Dropped by'} ${legend.name}, ${legend.title} · ${legend.region}</p>`:''}<div class="weapon-stats"><span>${w.damage} damage</span><span>${w.range} m</span><span>${w.cooldown}s</span>${w.element?`<span class="element">${ELEMENTS[w.element]||w.element}</span>`:''}</div><small class="heavy-note">${heavy||(w.kind==='melee'?'Quick strikes only':'No charged shot')}</small>${btn}</article>`;}).join('')}</div><h3>Supplies</h3><div class="supply-row"><span>${h.arrows} arrows</span><button data-action="rpg-supply" data-id="arrows" ${!dealer||s.coins<12?'disabled':''}>30 arrows · 12 coin</button></div><div class="supply-row"><span>${h.bolts} bolts</span><button data-action="rpg-supply" data-id="bolts" ${!dealer||s.coins<15?'disabled':''}>20 bolts · 15 coin</button></div><div class="supply-row"><span>${h.potions} healing draughts</span><button data-action="rpg-supply" data-id="potions" ${!dealer||s.coins<25?'disabled':''}>Healing draught · 25 coin</button></div>`};}
 if(name==='spellbook'){const known=(ARCHETYPES[h.archetype]||ARCHETYPES.human).spells;return{title:'The grimoire',kicker:known.length+' SPELLS · '+(ARCHETYPES[h.archetype]?.name||'HUMAN').toUpperCase(),html:tabs+`<div class="skill-points"><b>${points}</b><span>skill point${points===1?'':'s'} to spend<small>Earn one each level and more from every fallen legend. Rank II costs 1 point, rank III costs 2. Each rank adds 25% potency; rank III unlocks the spell’s mastery.</small></span></div><p class="merchant-note">Bind your spells to four quick-cast keys. Mana regenerates while you explore. Wizards know all sixteen arts. Press Z to select a spell without casting; Q casts it. Hold Sunlance’s key to channel it. Starfall, Winter’s veil and Thunderstorm show a ground targeting circle.</p><div class="spell-combos"><strong>Combine the elements</strong><p>Frost → Fire: <b>Shatter</b>, 65% bonus impact damage.<br>Frost → Lightning: <b>Conduction</b>, 40% bonus damage.<br>Fire → Lightning: <b>Overload</b>, 35% bonus damage and an arcane burst that leaps to nearby foes.<br>Fire burns over time. Ice extinguishes burning. Every foe has weaknesses; legends most of all.</p><small>Practise at the blue focus southwest of Eldermere’s plaza. Press E at the stone to refill mana and ready your spells.</small></div><div class="spell-grid">${Object.entries(SPELLS).map(([id,p])=>{const unlocked=known.includes(id),rank=unlocked?Math.max(1,Math.min(3,spellRank(h,id))):1,color=colorHex(p.color),owners=Object.values(ARCHETYPES).filter(c=>c.spells.includes(id)).map(c=>c.name);
   const pips=unlocked?`<span class="rank-pips" aria-label="Rank ${rank} of 3">${[1,2,3].map(r=>`<i class="${r<=rank?'on':''}">${ROMAN[r-1]}</i>`).join('')}</span>`:'';
   const upgrade=unlocked?`<button class="upgrade" data-action="rpg-upgrade" data-id="${id}" ${rank>=3||points<rank?'disabled':''}>${rank>=3?'Mastered':`Study rank ${ROMAN[rank]} · ${rank} point${rank>1?'s':''}`}</button>`:'';
   return`<article class="spell-card ${unlocked?'':'locked'} ${rank>=3?'mastered':''}" style="--spell-color:${color}"><div class="spell-title"><span class="spell-glyph">${p.glyph}</span><div><small>${p.school.toUpperCase()}</small><h3>${p.name}</h3></div>${pips}</div><p>${p.description}</p><p class="mastery ${rank>=3?'earned':''}"><b>${rank>=3?'Mastered':'Rank III mastery'}:</b> ${p.mastery||'Greater potency.'}</p><div class="weapon-stats"><span>${p.cost} mana${p.drain?' + '+p.drain+'/s':''}</span><span>${p.cooldown}s recharge</span>${rank>1?`<span class="potency">+${(rank-1)*25}% potency</span>`:''}</div>${unlocked?`<div class="spell-binding"><span>Bind to</span>${[0,1,2,3].map(n=>`<button data-action="rpg-bind" data-id="${id}" data-slot="${n}" class="${h.slots[n]===id?'bound':''}" aria-label="Bind ${p.name} to key ${n+1}">${n+1}</button>`).join('')}</div>${upgrade}`:`<small class="locked-note">Known to the ${owners.join(', ').replace(/, ([^,]*)$/,' and $1')||'Wizard'}.</small>`}</article>`;}).join('')}</div>`};}
 return null;
 },
 afterRender(name,s){const canvas=document.querySelector('#hero-preview');if(canvas)try{disposePreview=heroPreview(canvas,name==='characters'?selected:s.hero.archetype||'human');}catch{canvas.hidden=true;}},
 };
}
const $=id=>document.getElementById(id);
let lastEffects=null,notchKey=null;
const pct=(v,m)=>m>0&&Number.isFinite(v)?Math.max(0,Math.min(100,v/m*100)):0;
// Cheap per-frame pieces (charge ring, combo pips); main may call this every frame for a smooth ring.
export function updateCombatHUD(combat){const meter=$('charge-meter'),pips=$('combo-pips');
 if(meter){const c=Math.max(0,Math.min(1,Number(combat?.charge)||0)),on=!!combat?.charging&&c>0;meter.hidden=!on;if(on){meter.style.setProperty('--charge',c.toFixed(3));meter.classList.toggle('full',c>=1);}}
 if(pips){const k=Number.isInteger(combat?.combo)?combat.combo:-1;pips.classList.toggle('active',k>=0);pips.classList.toggle('finisher',k===2);[...pips.children].forEach((p,i)=>p.classList.toggle('lit',i<=k));}
}
function bossAttackName(b,def){const a=b.attack;if(!a)return null;if(typeof a==='string')return def?.attacks.find(x=>x.id===a)?.name||null;const id=a.id??a.attack??a.def?.id;const d=def?.attacks.find(x=>x.id===id);return{name:a.name??a.def?.name??d?.name,unblockable:!!(a.unblockable??a.def?.unblockable??d?.unblockable)};}
function updateBossBar(combat){const bar=$('boss-bar');if(!bar)return false;const b=combat?.boss,show=!!b&&!b.dead&&b.maxHealth>0;bar.hidden=!show;$('hud')?.classList.toggle('boss-fight',show);if(!show)return false;const def=BOSSES[b.boss]||{},phases=def.phases||[];
 bar.style.setProperty('--boss',colorHex(def.color??0xd9be85));$('boss-name').textContent=b.name||def.name||'';$('boss-title').textContent=b.title||def.title||'';const hp=pct(b.health,b.maxHealth);$('boss-health').style.width=hp+'%';const lag=$('boss-lag');if(lag)lag.style.width=hp+'%';
 const track=bar.querySelector('.boss-track');if(track&&notchKey!==b.boss){notchKey=b.boss;track.querySelectorAll('.boss-notch').forEach(n=>n.remove());for(const t of phases){const n=document.createElement('b');n.className='boss-notch';n.style.left=t*100+'%';track.append(n);}}
 if(track)[...track.querySelectorAll('.boss-notch')].forEach((n,i)=>n.classList.toggle('passed',hp<=phases[i]*100));
 const broken=(b.stagger||0)>0,atk=broken?null:bossAttackName(b,def),phase=Math.max(0,b.phase||0),poise=$('boss-poise');if(poise)poise.style.width=(broken?pct(b.stagger,3.2):pct(b.poise,b.maxPoise))+'%';
 bar.classList.toggle('broken',broken);bar.classList.toggle('casting',!!atk?.name);bar.classList.toggle('unblockable',!!atk?.unblockable);
 const label=$('boss-phase');if(label)label.textContent=broken?'BROKEN · strike now':atk?.name?atk.name+(atk.unblockable?' · unblockable, dodge!':''):'Phase '+ROMAN[Math.min(phase,4)]+' of '+ROMAN[Math.min(phases.length,4)]+' · '+Math.ceil(hp)+'%';
 return true;}
export function updateRPGHUD(s,combat){const h=s.hero,a=stats(h),weapon=WEAPONS[h.equipped]||WEAPONS.sword,fx=h.effects||{};$('hero-name').textContent=(ARCHETYPES[h.archetype]?.name||'Adventurer')+' · Lv. '+h.level;$('health-value').textContent=Math.ceil(h.health)+' / '+a.health;$('mana-value').textContent=Math.floor(h.mana)+' / '+a.mana;$('health-fill').style.width=pct(h.health,a.health)+'%';$('mana-fill').style.width=pct(h.mana,a.mana)+'%';const wn=$('weapon-name');wn.textContent=weapon.name;wn.classList.toggle('legendary',!!weapon.legendary);$('cycle-spell').setAttribute('aria-label','Select next spell. Current: '+(SPELLS[h.slots[h.selected]]?.name||''));const heavy=heavyText(weapon);$('weapon-ammo').textContent=weapon.ammo?h[weapon.ammo]+' '+weapon.ammo+(heavy?' · hold to draw':''):weapon.mana?weapon.mana+' mana / shot':heavy||'R to guard';$('potion-count').textContent=h.potions;const mana=$('mana-count');if(mana){const n=h.brews?.mana??0;mana.textContent=n;mana.parentElement.classList.toggle('empty',n<1);}
 const channel=combat?.channel??null;
 for(let i=0;i<4;i++){const id=h.slots[i],p=SPELLS[id],button=$('spell-'+i);if(!p||!button)continue;const rank=spellRank(h,id);button.querySelector('.hotbar-glyph').textContent=p.glyph;button.querySelector('.hotbar-name').textContent=p.name;const cd=h.cooldowns[id]||0,chan=!!channel&&channel.slot===i;button.querySelector('.hotbar-cost').textContent=chan?'Channelling':cd>.1?cd.toFixed(1)+'s':p.cost+' mana';button.classList.toggle('recharging',cd>.1&&!chan);button.classList.toggle('out-of-mana',h.mana<p.cost);button.classList.toggle('selected',h.selected===i);button.classList.toggle('channelling',chan);if(rank>1)button.dataset.rank=ROMAN[rank-1];else delete button.dataset.rank;button.style.setProperty('--spell-color',colorHex(p.color));button.setAttribute('aria-label',`${p.name}${rank>1?' rank '+rank:''}, key ${i+1}, ${Math.ceil(cd)} seconds recharge`);}
 const bossShown=updateBossBar(combat),boss=combat?.boss;
 const target=combat?.target?.()||null,bar=$('enemy-target'),showTarget=!!target&&!(bossShown&&target===boss);bar.hidden=!showTarget;if(showTarget){$('enemy-name').textContent=target.boss&&target.title?target.name+', '+target.title:target.name;const statuses=[],staggered=(target.stagger||0)>0;if(target.training)statuses.push('Practice · no rewards');if(staggered)statuses.push('Staggered');else if(target.windup>0)statuses.push('ATTACK INCOMING · parry, dodge or guard');if(target.burn>0)statuses.push('Burning');if(target.poison>0)statuses.push('Poisoned');if(target.iceLock>0)statuses.push('Frozen');else if(target.chill>0)statuses.push('Chilled');if(target.bind>0)statuses.push('Rooted');
  const aff=target.affinity&&typeof target.affinity==='object'?Object.entries(target.affinity).filter(([,v])=>Number.isFinite(v)):[];const weak=aff.filter(([,v])=>v>1.05).sort((x,y)=>y[1]-x[1])[0],resist=aff.filter(([,v])=>v<.6).sort((x,y)=>x[1]-y[1])[0];if(!target.training&&statuses.length<3){if(weak)statuses.push('Weak to '+(ELEMENTS[weak[0]]||weak[0]).toLowerCase());if(resist&&statuses.length<3)statuses.push('Resists '+(ELEMENTS[resist[0]]||resist[0]).toLowerCase());}
  $('enemy-status').textContent=statuses.join(' · ');bar.classList.toggle('threat',!staggered&&target.windup>0);bar.classList.toggle('staggered',staggered);$('enemy-health').style.width=pct(target.health,target.maxHealth)+'%';const poise=$('enemy-poise');if(poise){const has=target.maxPoise>0;poise.parentElement.hidden=!has||!!target.training;if(has)poise.style.width=(staggered?100:pct(target.poise,target.maxPoise))+'%';}}
 const active=[],add=(t,c)=>active.push(`<span class="fx ${c}">${t}</span>`),sec=v=>Math.ceil(v)+'s';
 if((combat?.riposte||0)>0)add('Riposte ready','riposte');if(fx.ward>0)add('Ward '+Math.ceil(h.shield||0),'good');if(fx.regen>0)add('Regenerating '+sec(fx.regen),'good');if(fx.wisp>0)add('Spirit '+sec(fx.wisp),'good');if(fx.haste>0)add('Windwalk '+sec(fx.haste),'good');if(fx.ironbark>0)add('Ironbark '+sec(fx.ironbark),'good');if(fx.swiftfoot>0)add('Swiftfoot '+sec(fx.swiftfoot),'good');if(fx.poison>0)add('Poisoned '+sec(fx.poison),'bad');if(fx.burn>0)add('Burning '+sec(fx.burn),'bad');if(fx.chill>0)add('Chilled '+sec(fx.chill),'bad');if(fx.root>0)add('Rooted','bad');if(channel)add('Channelling','info');if(combat?.blocking)add('Guarding','info');
 const html=active.join('');if(html!==lastEffects){lastEffects=html;$('active-effects').innerHTML=html;}
 updateCombatHUD(combat);
}
