import {ARCHETYPES,WEAPONS,SPELLS,stats,nextLevelXP} from './rpg.js';
import {heroPreview} from './models.js';
const colorHex=c=>'#'+c.toString(16).padStart(6,'0');
const tabs=`<nav class="rpg-tabs" aria-label="Character menus"><button data-action="rpg-tab" data-view="hero">Character</button><button data-action="rpg-tab" data-view="armory">Equipment</button><button data-action="rpg-tab" data-view="spellbook">Spellbook</button></nav>`;
export function createRPGPanels(){let selected='wizard',disposePreview=null;
 return{cleanup(){disposePreview?.();disposePreview=null;},select(id){if(ARCHETYPES[id])selected=id;},
 render(name,s,merchant){const h=s.hero,a=stats(h);if(name==='characters'){
  const chosen=ARCHETYPES[selected];return{title:'Choose your adventurer',kicker:'FOUR PATHS INTO ELDERWOOD',html:`<div class="character-choice"><div class="character-list">${Object.entries(ARCHETYPES).map(([id,c],i)=>`<button class="character-option ${id===selected?'selected':''}" style="--hero-color:${c.color}" data-action="rpg-preview" data-id="${id}" aria-pressed="${id===selected}"><span class="character-number">0${i+1}</span><span><strong>${c.name}</strong><small>${c.title}</small></span><span>↗</span></button>`).join('')}</div><div class="character-display"><canvas id="hero-preview" width="320" height="350" aria-label="3D preview of the selected ${chosen.name}"></canvas><span class="character-caption">${chosen.title}</span></div></div><p class="dialogue character-description">${chosen.description}</p><div class="character-stats"><span><b>${chosen.health}</b> Health</span><span><b>${chosen.mana}</b> Mana</span><span><b>${chosen.spells.length}</b> Spells</span></div><p class="merchant-note">Starts with ${chosen.gear.map(id=>WEAPONS[id].name).join(' and ')}. Every character can acquire all weapon families.</p><button class="primary" data-action="rpg-choose" data-id="${selected}">${h.archetype?'Become':'Play as'} ${chosen.name} <span>↗</span></button><p class="merchant-note">${h.archetype?'Changing character preserves your level, belongings, and current health and mana proportions.':'Your existing trading progress is preserved. You can change character later inside a settlement.'}</p>`};
 }
 if(name==='hero')return{title:ARCHETYPES[h.archetype]?.title||'Your adventurer',kicker:'LEVEL '+h.level+' · '+(ARCHETYPES[h.archetype]?.name||'HUMAN').toUpperCase(),html:tabs+`<div class="hero-summary"><div><p class="dialogue">${ARCHETYPES[h.archetype]?.description||'Choose the path you will follow.'}</p><div class="character-stats"><span><b>${Math.ceil(h.health)} / ${a.health}</b> Health</span><span><b>${Math.floor(h.mana)} / ${a.mana}</b> Mana</span><span><b>${h.kills}</b> Foes defeated</span></div><p class="merchant-note">${h.xp} / ${nextLevelXP(h)} XP toward the next level · Level cap 20</p><div class="xp-track"><i style="width:${h.xp/nextLevelXP(h)*100}%"></i></div></div><canvas id="hero-preview" width="320" height="350" aria-label="Your current character in 3D"></canvas></div><div class="dialogue-actions"><button data-action="rpg-tab" data-view="characters">Change character in town</button><button data-action="rpg-potion" ${h.potions<1||h.health>=a.health?'disabled':''}>Drink healing draught · ${h.potions} left</button></div><p class="merchant-note">Left click / Space attacks · R or right mouse guards · F drinks a draught. Keys 1–4 cast spells; Q repeats the selected spell. Mouse wheel cycles weapons. Villagers and peaceful wildlife are not combat targets.</p>`};
 if(name==='armory'){const dealer=merchant&&['rowan','gareth'].includes(merchant.id);return{title:dealer?'Weapons & provisions':'Your armory',kicker:dealer?'FORGED FOR THE OPEN ROAD':'EQUIPMENT · '+h.weapons.length+' / 13',html:tabs+`<p class="merchant-note">${dealer?'Purchase and equip weapons here.':'Equip anything you own. Rowan in Eldermere and Gareth in Ironhold sell every weapon and combat supplies.'} <b class="trade-balance">${s.coins} coin</b></p><div class="weapon-grid">${Object.entries(WEAPONS).map(([id,w])=>{const owned=h.weapons.includes(id),equipped=h.equipped===id;return`<article class="weapon-card ${equipped?'equipped':''}"><div class="weapon-card-top"><span>${w.family}</span><small>${equipped?'EQUIPPED':owned?'OWNED':w.price+' COIN'}</small></div><h3>${w.name}</h3><p>${w.description}</p><div class="weapon-stats"><span>${w.damage} damage</span><span>${w.range} m</span><span>${w.cooldown}s</span></div><button data-action="${owned?'rpg-equip':'rpg-buy'}" data-id="${id}" ${equipped||(!owned&&(!dealer||s.coins<w.price))?'disabled':''}>${equipped?'Equipped':owned?'Equip':dealer?'Buy · '+w.price+' coin':'Available from a merchant'}</button></article>`;}).join('')}</div><h3>Supplies</h3><div class="supply-row"><span>${h.arrows} arrows</span><button data-action="rpg-supply" data-id="arrows" ${!dealer||s.coins<12?'disabled':''}>30 arrows · 12 coin</button></div><div class="supply-row"><span>${h.bolts} bolts</span><button data-action="rpg-supply" data-id="bolts" ${!dealer||s.coins<15?'disabled':''}>20 bolts · 15 coin</button></div><div class="supply-row"><span>${h.potions} healing draughts</span><button data-action="rpg-supply" data-id="potions" ${!dealer||s.coins<25?'disabled':''}>Healing draught · 25 coin</button></div>`};}
 if(name==='spellbook'){const known=(ARCHETYPES[h.archetype]||ARCHETYPES.human).spells;return{title:'The grimoire',kicker:known.length+' SPELLS · '+(ARCHETYPES[h.archetype]?.name||'HUMAN').toUpperCase(),html:tabs+`<p class="merchant-note">Bind your spells to four quick-cast keys. Mana regenerates while you explore. Wizards know all twelve arts. Press Z to select a spell without casting; Q casts it. Starfall and Winter’s veil show a ground targeting circle.</p><div class="spell-combos"><strong>Combine the elements</strong><p>Frost → Fire: <b>Shatter</b>, 65% bonus impact damage.<br>Frost → Lightning: <b>Conduction</b>, 40% bonus damage.<br>Fire burns over time. Ice extinguishes burning.</p><small>Practise at the blue focus southwest of Eldermere’s plaza. Press E at the stone to refill mana and ready your spells.</small></div><div class="spell-grid">${Object.entries(SPELLS).map(([id,p])=>{const unlocked=known.includes(id);return`<article class="spell-card ${unlocked?'':'locked'}" style="--spell-color:${colorHex(p.color)}"><div class="spell-title"><span class="spell-glyph">${p.glyph}</span><div><small>${p.school.toUpperCase()}</small><h3>${p.name}</h3></div></div><p>${p.description}</p><div class="weapon-stats"><span>${p.cost} mana</span><span>${p.cooldown}s recharge</span></div>${unlocked?`<div class="spell-binding"><span>Bind to</span>${[0,1,2,3].map(n=>`<button data-action="rpg-bind" data-id="${id}" data-slot="${n}" class="${h.slots[n]===id?'bound':''}" aria-label="Bind ${p.name} to key ${n+1}">${n+1}</button>`).join('')}</div>`:'<small class="locked-note">Choose a Wizard to master this art.</small>'}</article>`;}).join('')}</div>`};}
 return null;
 },
 afterRender(name,s){const canvas=document.querySelector('#hero-preview');if(canvas)try{disposePreview=heroPreview(canvas,name==='characters'?selected:s.hero.archetype||'human');}catch{canvas.hidden=true;}},
 };
}
export function updateRPGHUD(s,combat){const h=s.hero,a=stats(h),weapon=WEAPONS[h.equipped],$=id=>document.getElementById(id);$('hero-name').textContent=(ARCHETYPES[h.archetype]?.name||'Adventurer')+' · Lv. '+h.level;$('health-value').textContent=Math.ceil(h.health)+' / '+a.health;$('mana-value').textContent=Math.floor(h.mana)+' / '+a.mana;$('health-fill').style.width=h.health/a.health*100+'%';$('mana-fill').style.width=h.mana/a.mana*100+'%';$('weapon-name').textContent=weapon.name;$('cycle-spell').setAttribute('aria-label','Select next spell. Current: '+SPELLS[h.slots[h.selected]].name);$('weapon-ammo').textContent=weapon.ammo?h[weapon.ammo]+' '+weapon.ammo:weapon.mana?weapon.mana+' mana / shot':'R to guard';$('potion-count').textContent=h.potions;
 for(let i=0;i<4;i++){const p=SPELLS[h.slots[i]],button=$('spell-'+i);button.querySelector('.hotbar-glyph').textContent=p.glyph;button.querySelector('.hotbar-name').textContent=p.name;const cd=h.cooldowns[h.slots[i]]||0;button.querySelector('.hotbar-cost').textContent=cd>.1?cd.toFixed(1)+'s':p.cost+' mana';button.classList.toggle('recharging',cd>.1);button.classList.toggle('out-of-mana',h.mana<p.cost);button.classList.toggle('selected',h.selected===i);button.style.setProperty('--spell-color',colorHex(p.color));button.setAttribute('aria-label',`${p.name}, key ${i+1}, ${Math.ceil(cd)} seconds recharge`);}
 const target=combat.target(),bar=$('enemy-target');bar.hidden=!target;if(target){$('enemy-name').textContent=target.name;const statuses=[];if(target.training)statuses.push('Practice · no rewards');if(target.windup>0)statuses.push('ATTACK INCOMING · guard or move');if(target.burn>0)statuses.push('Burning');if(target.iceLock>0)statuses.push('Frozen');else if(target.chill>0)statuses.push('Chilled');if(target.bind>0)statuses.push('Rooted');$('enemy-status').textContent=statuses.join(' · ');bar.classList.toggle('threat',target.windup>0);$('enemy-health').style.width=Math.max(0,target.health/target.maxHealth*100)+'%';}
 const active=[];if(h.effects.ward>0)active.push('Ward '+Math.ceil(h.shield));if(h.effects.wisp>0)active.push('Spirit '+Math.ceil(h.effects.wisp)+'s');if(h.effects.haste>0)active.push('Windwalk '+Math.ceil(h.effects.haste)+'s');if(combat.blocking)active.push('Guarding');$('active-effects').textContent=active.join(' · ');
}
