/** Persistent fantasy progression, independent from rendering and the trading engine. */
import {BOSSES,BOSS_KEYS} from './bosses.js';
export const ARCHETYPES = {
 human: { name:'Human', title:'The Ironbound', description:'An adaptable adventurer with a strong guard and a steady sword arm.', health:125, mana:85, speed:1, melee:1.15, ranged:1, magic:1, armor:.84, regen:5, eye:1.72, color:'#d8b879', gear:['sword','crossbow'], spells:['fireball','heal','ward','haste','sunlance','earthshatter'] },
 elf: { name:'Elf', title:'The Moonwood Ranger', description:'Swift of foot, deadly with a bow, and attuned to the living forest.', health:95, mana:125, speed:1.16, melee:.95, ranged:1.4, magic:1.12, armor:.96, regen:7, eye:1.8, color:'#89d3b1', gear:['longbow','dagger'], spells:['frost','heal','roots','blink','wisp','haste','thunderstorm'] },
 wizard: { name:'Wizard', title:'The Astral Scholar', description:'A master of sixteen arcane arts, from falling stars to summoned spirits.', health:85, mana:190, speed:.98, melee:.8, ranged:.9, magic:1.45, armor:1.04, regen:10, eye:1.72, color:'#b9a2f4', gear:['emberstaff','wand'], spells:['fireball','frost','lightning','meteor','heal','ward','blink','roots','nova','wisp','blizzard','haste','sunlance','earthshatter','thunderstorm','siphon'] },
 ogre: { name:'Ogre', title:'The Stoneborn', description:'A towering warrior whose hammer and earth magic scatter whole warbands.', health:200, mana:65, speed:.88, melee:1.55, ranged:.85, magic:.9, armor:.72, regen:4, eye:2.1, color:'#c3ca8d', gear:['warhammer','axe'], spells:['nova','ward','roots','heal','earthshatter','siphon'] }
};
// heavy: the charged attack released after holding attack. move names drive animation and behaviour.
export const WEAPONS = {
 sword: {name:'Wayfarer’s sword',family:'Sword',damage:24,range:3,cooldown:.58,price:45,kind:'melee',arc:.56,poise:14,color:0xc2d2db,heavy:{move:'rising',mult:2.1,arc:.3,range:3.4},description:'A balanced steel blade with a broad, reliable cut.'},
 dagger: {name:'Moonfang dagger',family:'Dagger',damage:15,range:2.3,cooldown:.28,price:65,kind:'melee',arc:.7,poise:7,color:0xa5decb,heavy:{move:'flurry',mult:1.05,hits:3,arc:.6,stamina:18},description:'A quick silver edge for close encounters.'},
 axe: {name:'Woodland battleaxe',family:'Axe',damage:39,range:3.1,cooldown:.92,price:125,kind:'melee',arc:.46,poise:22,color:0xc9b38a,heavy:{move:'cleave',mult:2.2,arc:-.2,range:3.3},description:'Heavy chopping blows strike several nearby foes.'},
 mace: {name:'Dawnsteel mace',family:'Mace',damage:31,range:2.8,cooldown:.7,price:155,kind:'melee',arc:.7,stun:.8,poise:28,color:0xe6ce84,heavy:{move:'concuss',mult:2,arc:.6,stun:2},description:'Crushing strikes briefly stagger an enemy.'},
 greatsword: {name:'Kingsguard greatsword',family:'Greatsword',damage:50,range:3.8,cooldown:1.15,price:260,kind:'melee',arc:.3,poise:30,color:0xc1d5df,heavy:{move:'whirl',mult:1.8,arc:-1,range:4.3},description:'Long, sweeping cuts punish groups of enemies.'},
 spear: {name:'Ashwood spear',family:'Spear',damage:29,range:5,cooldown:.75,price:130,kind:'melee',arc:.88,poise:16,color:0xc1ced2,heavy:{move:'lunge',mult:2.2,arc:.8,range:5.4,lunge:4.5},description:'Reach past your opponent’s guard with a precise thrust.'},
 warhammer: {name:'Stonebreaker',family:'Warhammer',damage:64,range:3.4,cooldown:1.45,price:310,kind:'melee',arc:.42,stun:1.1,poise:42,color:0xaeb7a3,heavy:{move:'slam',mult:1.9,radius:4.6},description:'An immense rune-cut hammer with a staggering impact.'},
 longbow: {name:'Moonwood longbow',family:'Bow',damage:30,range:60,cooldown:.75,price:165,kind:'ranged',speed:42,ammo:'arrows',poise:10,color:0xa2d7b4,heavy:{move:'draw',mult:2.2,speed:1.5,pierce:3,stamina:16},description:'A graceful bow with excellent reach. Uses arrows.'},
 crossbow: {name:'Ironhold crossbow',family:'Crossbow',damage:46,range:65,cooldown:1.25,price:240,kind:'ranged',speed:55,ammo:'bolts',poise:18,color:0xd6c28f,description:'A slow, powerful ranged weapon. Uses bolts.'},
 chakram: {name:'Returning sunblade',family:'Chakram',damage:23,range:28,cooldown:.55,price:220,kind:'ranged',speed:28,poise:8,color:0xffcc75,description:'An enchanted throwing ring that never consumes ammunition.'},
 emberstaff: {name:'Staff of embers',family:'Fire staff',damage:25,range:42,cooldown:.68,price:185,kind:'magic',speed:23,mana:4,poise:5,color:0xff9450,description:'A carved staff that launches bolts of living flame.'},
 froststaff: {name:'Winterglass staff',family:'Ice staff',damage:21,range:48,cooldown:.62,price:225,kind:'magic',speed:30,mana:4,slow:2,poise:5,color:0x91e4ff,description:'Frozen crystal bolts slow their target.'},
 wand: {name:'Starseeker wand',family:'Wand',damage:13,range:36,cooldown:.3,price:95,kind:'magic',speed:38,mana:2,poise:3,color:0xc4a2ff,description:'Rapid arcane darts from a silver-tipped wand.'},
 frostfang: {name:'Frostfang',family:'Sword',damage:36,range:3.2,cooldown:.55,price:0,legendary:'frost',kind:'melee',arc:.52,element:'ice',chill:3,poise:18,color:0x9fe4ff,heavy:{move:'rising',mult:2.2,arc:.28,range:3.5,wave:'ice'},description:'Hrimfang’s shed fang, honed to a blade. Cuts chill foes; heavy strikes loose a frost wave.'},
 thornstaff: {name:'Mirewood thornstaff',family:'Nature staff',damage:30,range:44,cooldown:.55,price:0,legendary:'mire',kind:'magic',speed:30,mana:3,element:'nature',bind:.7,poison:3,poise:8,color:0x9bdc6c,description:'Morwen’s living staff. Thorn bolts poison their target and briefly root it.'},
 cindermaul: {name:'Cinderheart maul',family:'Warhammer',damage:76,range:3.5,cooldown:1.3,price:0,legendary:'cinder',kind:'melee',arc:.42,stun:1.1,element:'fire',burn:3,poise:50,color:0xffa05a,heavy:{move:'slam',mult:2,radius:5.2,fire:true},description:'Its head still holds the Colossus’s molten heart. Every blow sets foes ablaze.'},
 riftblade: {name:'Riftblade of the Hollow King',family:'Greatsword',damage:64,range:4,cooldown:.95,price:0,legendary:'hollow',kind:'melee',arc:.32,element:'arcane',poise:36,color:0xc6a4ff,heavy:{move:'whirl',mult:1.9,arc:-1,range:4.5,wave:'rift'},description:'The fallen king’s blade. Heavy strikes send a crescent of rift energy.'}
};
// Channelled spells spend cost once, then drain mana per second while held (up to channel seconds).
export const SPELLS = {
 fireball:{name:'Fireball',school:'Ember',glyph:'☀',cost:18,cooldown:2.5,damage:34,range:42,radius:3.8,speed:22,color:0xff8b43,description:'Hurl a blazing orb that explodes and burns enemies. Shatters chilled targets for 65% bonus impact damage.',mastery:'The blast leaves the ground burning.'},
 frost:{name:'Frost lance',school:'Winter',glyph:'❄',cost:14,cooldown:2,damage:27,range:45,speed:34,freeze:3,color:0x92ddff,description:'Launch an ice lance that freezes a foe. Follow with fire or lightning for an elemental combination.',mastery:'The lance pierces through two more enemies.'},
 lightning:{name:'Chain lightning',school:'Storm',glyph:'ϟ',cost:27,cooldown:4,damage:31,range:25,color:0xb5c9ff,description:'Forked lightning leaps between four enemies. Chilled targets conduct 40% more damage; burning targets overload.',mastery:'The lightning leaps between six enemies.'},
 meteor:{name:'Starfall',school:'Celestial',glyph:'✷',cost:45,cooldown:10,damage:74,range:27,radius:6,color:0xffb276,description:'Call a blazing meteor into the targeting circle, scattering and burning nearby enemies.',mastery:'Two lesser stars follow the first.'},
 heal:{name:'Restoration',school:'Life',glyph:'✚',cost:24,cooldown:7,healing:48,color:0x89efb7,description:'Mend your wounds in a spiral of luminous leaves.',mastery:'Also restores 6 health per second for six seconds.'},
 ward:{name:'Arcane ward',school:'Protection',glyph:'◇',cost:22,cooldown:12,duration:9,shield:75,color:0x9baeff,description:'A translucent barrier absorbs damage for nine seconds.',mastery:'Reflects 40% of absorbed damage at the attacker.'},
 blink:{name:'Blink step',school:'Space',glyph:'»',cost:20,cooldown:5,range:9,color:0xcdb1ff,description:'Flash forward along a clear path. Walls and rivers still stop you.',mastery:'Leaves a burst of force where you stood.'},
 roots:{name:'Grasping roots',school:'Nature',glyph:'♧',cost:23,cooldown:7,damage:14,duration:5,radius:7,color:0xaad88b,description:'Roots erupt around you and bind nearby enemies. Legendary foes shrug off the binding.',mastery:'Thorned roots poison everything they bind.'},
 nova:{name:'Arcane nova',school:'Force',glyph:'✧',cost:30,cooldown:7,damage:40,radius:7,color:0xc5a0ff,description:'Release a ring of force that damages and pushes enemies away.',mastery:'A wider ring that staggers what it strikes.'},
 wisp:{name:'Spirit companion',school:'Summoning',glyph:'◉',cost:35,cooldown:24,duration:18,damage:16,range:20,color:0x99f4e2,description:'Summon a friendly wisp that follows you and fires at your foes.',mastery:'The spirit strikes twice as often.'},
 blizzard:{name:'Winter’s veil',school:'Winter',glyph:'❅',cost:36,cooldown:12,duration:7,damage:9,range:20,radius:6,color:0xbbebff,description:'Summon a swirling snowstorm that damages, chills and slows enemies, preparing elemental combinations.',mastery:'The final gust freezes enemies solid.'},
 haste:{name:'Windwalk',school:'Wind',glyph:'≋',cost:25,cooldown:18,duration:11,color:0xc3eab3,description:'Ride a tailwind to move much faster for eleven seconds.',mastery:'Your attacks also quicken by 20%.'},
 sunlance:{name:'Sunlance',school:'Radiant',glyph:'✺',cost:10,drain:15,channel:4,cooldown:3,damage:34,range:26,color:0xffe38a,description:'Hold the key to channel a beam of sunlight, 34 damage per second. Undead and the Hollow suffer greatly.',mastery:'The beam mends you for 20% of the damage it deals.'},
 earthshatter:{name:'Earthshatter',school:'Earth',glyph:'◬',cost:28,cooldown:6,damage:46,range:15,width:3,poise:60,color:0xd9ad6c,description:'Stone spikes erupt in a line ahead, staggering whatever they strike.',mastery:'A longer line, and a second wave follows.'},
 thunderstorm:{name:'Thunderstorm',school:'Storm',glyph:'☈',cost:40,cooldown:14,damage:30,range:24,radius:9,bolts:6,duration:2.4,color:0xaebcff,description:'Call a storm over the targeting circle that strikes enemies again and again.',mastery:'The storm strikes ten times.'},
 siphon:{name:'Soul siphon',school:'Shadow',glyph:'☾',cost:22,cooldown:6,damage:42,range:22,heal:.6,color:0xe0739b,description:'Tear life from the enemy you face and take 60% of it for yourself.',mastery:'Healing beyond full health becomes a ward.'}
};
// size: projectile hit sphere (radius, height). onHit: statuses applied to the hero. ranged: keeps distance and fires bolts.
export const ENEMY_DEFS={
 wolf:{name:'Briar wolf',health:52,damage:9,speed:2.8,xp:22,coin:9,poise:24,size:{r:.7,y:.85}},
 goblin:{name:'Road goblin',health:72,damage:12,speed:2.2,xp:34,coin:15,poise:34},
 skeleton:{name:'Hollow knight',health:92,damage:15,speed:1.9,xp:46,coin:21,poise:60,affinity:{radiant:1.5}},
 wraith:{name:'Rift wraith',health:110,damage:17,speed:2.3,xp:58,coin:27,poise:45,affinity:{radiant:1.6,shadow:.5}},
 sentinel:{name:'Runestone guardian',health:260,damage:25,speed:1.5,xp:130,coin:75,poise:150,size:{r:1,y:1.6},affinity:{storm:.8,earth:.7},windup:1,cadence:1.7,reach:2},
 frostwolf:{name:'Rime wolf',health:84,damage:13,speed:3.1,xp:48,coin:17,poise:30,size:{r:.75,y:.9},affinity:{ice:.35,fire:1.4},onHit:{chill:2.5}},
 troll:{name:'Frost troll',health:280,damage:28,speed:1.75,xp:130,coin:58,poise:160,size:{r:1.2,y:1.8},affinity:{ice:.5,fire:1.35},windup:1.05,cadence:1.8,reach:2.1},
 thrall:{name:'Bog thrall',health:150,damage:18,speed:1.55,xp:64,coin:25,poise:70,affinity:{fire:1.5,nature:.4,radiant:1.4},onHit:{poison:4}},
 hexer:{name:'Mire hexer',health:96,damage:14,speed:2,xp:72,coin:31,poise:40,affinity:{storm:1.45,nature:.6},ranged:{range:17,keep:8,speed:15,color:0x9be36b,status:{slow:1.2},element:'nature'}},
 imp:{name:'Cinder imp',health:70,damage:12,speed:2.9,xp:58,coin:24,poise:24,size:{r:.6,y:.8},affinity:{fire:.2,ice:1.6},ranged:{range:16,keep:7,speed:18,color:0xff8a3d,status:{burn:2},element:'fire'}},
 cinderbrute:{name:'Cinder brute',health:250,damage:26,speed:1.65,xp:120,coin:52,poise:150,size:{r:1.2,y:1.8},affinity:{fire:.25,ice:1.5},onHit:{burn:3},windup:1.05,cadence:1.7,reach:2.1}
};
export const DEALERS=['rowan','gareth','halvard'];
// Herbalists brew satchel goods into draughts and tonics; tonic effects outlast ordinary buffs.
export const BREWS={
 mana:{name:'Mana draught',recipe:{herbs:2,berries:2},coin:4,restore:60,description:'Restores 60 mana at once. Press G to drink.'},
 ironbark:{name:'Ironbark tonic',recipe:{mushrooms:2,herbs:1},coin:8,duration:90,description:'Skin as hard as old bark: take 25% less damage for 90 seconds.'},
 swiftfoot:{name:'Swiftfoot tonic',recipe:{berries:2,mushrooms:1},coin:6,duration:90,description:'Stamina returns 60% faster and dodges cost a third less for 90 seconds.'}
};
const HERO_EFFECTS=['ward','haste','wisp','grace','regen','chill','poison','burn','root','ironbark','swiftfoot'],LONG_EFFECTS=['ironbark','swiftfoot'];
const SLAIN_KINDS=()=>[...Object.keys(ENEMY_DEFS),...Object.values(BOSSES).map(b=>b.kind)];
export function freshHero(){return{version:2,archetype:null,level:1,xp:0,health:125,mana:85,weapons:['sword'],equipped:'sword',slots:['fireball','heal','ward','haste'],selected:0,arrows:40,bolts:25,potions:3,kills:0,defeated:{},cooldowns:{},effects:{},shield:0,points:0,ranks:{},bosses:[],brews:{mana:0,ironbark:0,swiftfoot:0},slain:{},echoes:{}};}
// Version 1 heroes predate skill points: grant one per level already earned.
export function migrateHero(h){if(!h||typeof h!=='object'||Array.isArray(h))return h;if(h.version===1){h.version=2;h.points=Number.isSafeInteger(h.level)&&h.level>1?h.level-1:0;h.ranks={};h.bosses=[];}
 // Legends-era heroes gain an empty brew pouch, bestiary and echo record.
 if(h.version===2){if(h.brews===undefined)h.brews={mana:0,ironbark:0,swiftfoot:0};if(h.slain===undefined)h.slain={};if(h.echoes===undefined)h.echoes={};}return h;}
export function stats(h){const a=ARCHETYPES[h.archetype]||ARCHETYPES.human,legends=Array.isArray(h.bosses)?h.bosses.length:0;return{...a,health:a.health+(h.level-1)*9+legends*12,mana:a.mana+(h.level-1)*7+legends*10,power:1+(h.level-1)*.075+legends*.03};}
export const nextLevelXP=h=>h.level*75;
export const spellRank=(h,id)=>h.ranks?.[id]||1;
export const potency=(h,id)=>1+(spellRank(h,id)-1)*.25;
export function chooseArchetype(s,id){if(!Object.hasOwn(ARCHETYPES,id))return{ok:false,message:'Choose a character from the four available.'};const h=s.hero,first=h.archetype===null,old=stats(h),hpRatio=h.health/old.health,mpRatio=h.mana/old.mana;h.archetype=id;h.weapons=[...new Set([...h.weapons,...ARCHETYPES[id].gear])];h.equipped=ARCHETYPES[id].gear[0];h.slots=id==='wizard'?['fireball','frost','heal','blink']:ARCHETYPES[id].spells.slice(0,4);h.selected=0;const max=stats(h);h.health=first?max.health:Math.max(1,Math.min(max.health,hpRatio*max.health));h.mana=first?max.mana:Math.min(max.mana,mpRatio*max.mana);return{ok:true,message:ARCHETYPES[id].name+' · '+ARCHETYPES[id].title};}
export function buyWeapon(s,id){const w=Object.hasOwn(WEAPONS,id)?WEAPONS[id]:null;if(!w)return{ok:false,message:'Unknown weapon.'};if(s.hero.weapons.includes(id))return{ok:false,message:'You already own this weapon.'};if(w.legendary)return{ok:false,message:'Only a fallen legend can yield this weapon.'};if(s.coins<w.price)return{ok:false,message:'You need '+w.price+' coin.'};s.coins-=w.price;s.hero.weapons.push(id);s.hero.equipped=id;return{ok:true,message:w.name+' acquired and equipped.'};}
export function equipWeapon(s,id){if(!s.hero.weapons.includes(id)||!Object.hasOwn(WEAPONS,id))return{ok:false,message:'You do not own that weapon.'};s.hero.equipped=id;return{ok:true,message:WEAPONS[id].name+' equipped.'};}
export function assignSpell(s,slot,id){if(!Number.isInteger(slot)||slot<0||slot>3||!ARCHETYPES[s.hero.archetype]?.spells.includes(id))return{ok:false,message:'That spell is not available to this character.'};s.hero.slots[slot]=id;return{ok:true,message:SPELLS[id].name+' bound to key '+(slot+1)+'.'};}
export function upgradeSpell(s,id){const h=s.hero;if(!Object.hasOwn(SPELLS,id)||!ARCHETYPES[h.archetype]?.spells.includes(id))return{ok:false,message:'This character cannot study that spell.'};const r=spellRank(h,id);if(r>=3)return{ok:false,message:SPELLS[id].name+' is already mastered.'};if(h.points<r)return{ok:false,message:'You need '+r+' skill point'+(r>1?'s':'')+'.'};h.points-=r;h.ranks[id]=r+1;return{ok:true,message:SPELLS[id].name+' · rank '+(r+1)+(r+1===3?' · '+SPELLS[id].mastery:' · 25% more potent')};}
export function spendCast(h,id){const p=SPELLS[id];if(!p||!ARCHETYPES[h.archetype]?.spells.includes(id))return{ok:false,message:'This character does not know that spell.'};if(h.health<=0)return{ok:false,message:'Recover before casting.'};if((h.cooldowns[id]||0)>0)return{ok:false,message:p.name+' is recharging.'};if(h.mana<p.cost)return{ok:false,message:'Not enough mana. It regenerates over time.'};if(id==='heal'&&h.health>=stats(h).health)return{ok:false,message:'You are already at full health.'};h.mana-=p.cost;h.cooldowns[id]=p.cooldown;return{ok:true};}
export function spendAttack(h){const w=WEAPONS[h.equipped];if(!w||!h.weapons.includes(h.equipped)||h.health<=0||(h.cooldowns.attack||0)>0)return{ok:false,message:''};if(w.ammo&&h[w.ammo]<=0)return{ok:false,message:'Out of '+w.ammo+'. Buy supplies from Rowan, Gareth or Halvard.'};if(w.mana&&h.mana<w.mana)return{ok:false,message:'Not enough mana. Equip a blade while you recover.'};if(w.ammo)h[w.ammo]--;h.mana-=w.mana||0;h.cooldowns.attack=w.cooldown*(h.effects.haste>0&&spellRank(h,'haste')===3?.8:1);return{ok:true,weapon:w};}
export function tickHero(h,dt){if(!Number.isFinite(dt)||dt<=0)return;for(const key of Object.keys(h.cooldowns))h.cooldowns[key]=Math.max(0,h.cooldowns[key]-dt);for(const key of Object.keys(h.effects))h.effects[key]=Math.max(0,h.effects[key]-dt);if(!h.effects.ward)h.shield=0;h.mana=Math.min(stats(h).mana,h.mana+stats(h).regen*dt);}
export function hurtHero(h,amount,blocking=false){if(!Number.isFinite(amount)||amount<=0||h.health<=0||h.effects.grace>0)return 0;let damage=amount*stats(h).armor*(blocking?.35:1)*(h.effects.ironbark>0?.75:1);if(h.shield>0){const absorb=Math.min(h.shield,damage);h.shield-=absorb;damage-=absorb;}h.health=Math.max(0,h.health-damage);return damage;}
function gainXP(h,xp){h.xp+=xp;let levels=0;while(h.level<20&&h.xp>=nextLevelXP(h)){h.xp-=nextLevelXP(h);h.level++;levels++;}if(h.level===20)h.xp=Math.min(h.xp,nextLevelXP(h));h.points+=levels;if(levels){h.health=stats(h).health;h.mana=stats(h).mana;}return levels;}
export const grantXP=(h,xp)=>gainXP(h,Math.max(0,Math.round(xp)));
export function noteSlain(h,kind){if(!h.slain||typeof h.slain!=='object')h.slain={};if(SLAIN_KINDS().includes(kind))h.slain[kind]=Math.min(1e9,(h.slain[kind]||0)+1);}
// Each hostile pays once per day; a matching open bounty counts the kill.
export function rewardKill(s,enemy){const h=s.hero;if(!/^hostile-\d+$/.test(enemy.id))return{rewarded:false,levels:0};if(h.defeated[enemy.id]===s.day)return{rewarded:false,levels:0};h.defeated[enemy.id]=s.day;h.kills++;s.coins+=enemy.coin;noteSlain(h,enemy.kind);let bounty=null;for(const b of Array.isArray(s.bounties)?s.bounties:[])if(!b.complete&&b.kind===enemy.kind&&b.have<b.need){b.have++;bounty=b;break;}return{rewarded:true,levels:gainXP(h,enemy.xp),bounty};}
// A legend pays out once, forever: sigil, legendary weapon, skill points, coin and experience.
export function rewardBoss(s,key){const b=Object.hasOwn(BOSSES,key)?BOSSES[key]:null,h=s.hero;if(!b||h.bosses.includes(key))return{rewarded:false,levels:0};h.bosses.push(key);h.kills++;s.coins+=b.coin;h.points+=b.points;noteSlain(h,b.kind);const levels=gainXP(h,b.xp),weapon=h.weapons.includes(b.weapon)?null:b.weapon;if(weapon)h.weapons.push(weapon);h.health=stats(h).health;h.mana=stats(h).mana;return{rewarded:true,levels,weapon,sigil:b.sigil};}
// Echoes of fallen legends can be bested once per day for a share of the original purse.
export const ECHO={health:1.35,damage:1.25,speed:1.15,coin:.4,xp:.35};
export function rewardEcho(s,key){const b=Object.hasOwn(BOSSES,key)?BOSSES[key]:null,h=s.hero;if(!b||!h.bosses.includes(key)||h.echoes?.[key]===s.day)return{rewarded:false,levels:0};h.echoes[key]=s.day;h.kills++;noteSlain(h,b.kind);const coin=Math.round(b.coin*ECHO.coin);s.coins+=coin;return{rewarded:true,coin,levels:gainXP(h,b.xp*ECHO.xp)};}
export function drinkBrew(s,id){const b=Object.hasOwn(BREWS,id)?BREWS[id]:null,h=s.hero;if(!b)return{ok:false,message:'Unknown brew.'};if(!(h.brews?.[id]>0))return{ok:false,message:'You carry no '+b.name.toLowerCase()+'. An herbalist can brew one.'};
 if(id==='mana'){const max=stats(h).mana;if(h.mana>=max)return{ok:false,message:'Your mana is already full.'};h.brews.mana--;h.mana=Math.min(max,h.mana+b.restore);return{ok:true,message:b.name+' · mana restored.'};}
 h.brews[id]--;h.effects[id]=b.duration;return{ok:true,message:b.name+' · '+b.duration+' seconds.'};}
export function recover(s){const fee=Math.min(30,Math.floor(s.coins*.1));s.coins-=fee;s.position={x:0,z:28,yaw:0,pitch:0};s.hero.health=stats(s.hero).health;s.hero.mana=stats(s.hero).mana;s.hero.shield=0;s.hero.effects={grace:8};return{ok:true,message:'Rescued at Eldermere · '+fee+' coin paid for your recovery.'};}
export function drinkPotion(s){if(s.hero.potions<1)return{ok:false,message:'No healing draughts left. Visit Rowan, Gareth or Halvard.'};const e=s.hero.effects,ailing=e.poison>0||e.burn>0||e.chill>0||e.root>0;if(s.hero.health>=stats(s.hero).health&&!ailing)return{ok:false,message:'You are already at full health.'};s.hero.potions--;s.hero.health=Math.min(stats(s.hero).health,s.hero.health+65);for(const k of ['poison','burn','chill','root'])delete e[k];return{ok:true,message:'Healing draught · restored up to 65 health'+(ailing?' and cleansed your ailments.':'.')};}
export function buySupply(s,id){const offers={arrows:{qty:30,cost:12},bolts:{qty:20,cost:15},potions:{qty:1,cost:25}};const offer=Object.hasOwn(offers,id)?offers[id]:null;if(!offer||s.coins<offer.cost)return{ok:false,message:'You do not have enough coin for those supplies.'};if(s.hero[id]+offer.qty>9999)return{ok:false,message:'You cannot carry more of that supply.'};s.coins-=offer.cost;s.hero[id]+=offer.qty;return{ok:true,message:'Purchased '+offer.qty+' '+id+'.'};}
export function validHero(h){const n=(v,a,b)=>typeof v==='number'&&Number.isFinite(v)&&v>=a&&v<=b,i=(v,a,b)=>Number.isSafeInteger(v)&&v>=a&&v<=b,plain=v=>v&&typeof v==='object'&&!Array.isArray(v);if(!plain(h)||h.version!==2||(h.archetype!==null&&!Object.hasOwn(ARCHETYPES,h.archetype))||!i(h.level,1,20)||!i(h.xp,0,1500)||!i(h.kills,0,1e9)||!i(h.selected,0,3)||!n(h.shield,0,150)||!i(h.points,0,500))return false;
 if(!Array.isArray(h.bosses)||h.bosses.length>BOSS_KEYS.length||new Set(h.bosses).size!==h.bosses.length||!h.bosses.every(k=>BOSS_KEYS.includes(k)))return false;
 if(!n(h.health,0,stats(h).health)||!n(h.mana,0,stats(h).mana))return false;
 if(!plain(h.ranks)||!Object.entries(h.ranks).every(([k,v])=>Object.hasOwn(SPELLS,k)&&(v===2||v===3)))return false;
 const weaponCount=Object.keys(WEAPONS).length;if(!Array.isArray(h.weapons)||h.weapons.length<1||h.weapons.length>weaponCount||new Set(h.weapons).size!==h.weapons.length||!h.weapons.every(w=>Object.hasOwn(WEAPONS,w))||!h.weapons.includes(h.equipped))return false;
 const known=(ARCHETYPES[h.archetype]||ARCHETYPES.human).spells;if(!Array.isArray(h.slots)||h.slots.length!==4||!h.slots.every(p=>known.includes(p)))return false;for(const key of ['arrows','bolts','potions'])if(!i(h[key],0,9999))return false;if(!plain(h.defeated)||!Object.entries(h.defeated).every(([k,v])=>/^hostile-\d+$/.test(k)&&i(v,1,1e7)))return false;
 for(const field of ['cooldowns','effects']){if(!plain(h[field]))return false;const allowed=field==='cooldowns'?['attack',...Object.keys(SPELLS)]:HERO_EFFECTS;if(!Object.entries(h[field]).every(([k,v])=>allowed.includes(k)&&n(v,0,LONG_EFFECTS.includes(k)?90:60)))return false;}
 if(!plain(h.brews)||!Object.keys(BREWS).every(k=>i(h.brews[k],0,99))||Object.keys(h.brews).length!==Object.keys(BREWS).length)return false;
 const kinds=SLAIN_KINDS();if(!plain(h.slain)||!Object.entries(h.slain).every(([k,v])=>kinds.includes(k)&&i(v,1,1e9)))return false;
 if(!plain(h.echoes)||!Object.entries(h.echoes).every(([k,v])=>h.bosses.includes(k)&&i(v,1,1e7)))return false;return true;}
