/** Persistent fantasy progression, independent from rendering and the trading engine. */
export const ARCHETYPES = {
 human: { name:'Human', title:'The Ironbound', description:'An adaptable adventurer with a strong guard and a steady sword arm.', health:125, mana:85, speed:1, melee:1.15, ranged:1, magic:1, armor:.84, regen:5, eye:1.72, color:'#d8b879', gear:['sword','crossbow'], spells:['fireball','heal','ward','haste'] },
 elf: { name:'Elf', title:'The Moonwood Ranger', description:'Swift of foot, deadly with a bow, and attuned to the living forest.', health:95, mana:125, speed:1.16, melee:.95, ranged:1.4, magic:1.12, armor:.96, regen:7, eye:1.8, color:'#89d3b1', gear:['longbow','dagger'], spells:['frost','heal','roots','blink','wisp','haste'] },
 wizard: { name:'Wizard', title:'The Astral Scholar', description:'A master of twelve arcane arts, from falling stars to summoned spirits.', health:85, mana:190, speed:.98, melee:.8, ranged:.9, magic:1.45, armor:1.04, regen:10, eye:1.72, color:'#b9a2f4', gear:['emberstaff','wand'], spells:['fireball','frost','lightning','meteor','heal','ward','blink','roots','nova','wisp','blizzard','haste'] },
 ogre: { name:'Ogre', title:'The Stoneborn', description:'A towering warrior whose hammer and earth magic scatter whole warbands.', health:200, mana:65, speed:.88, melee:1.55, ranged:.85, magic:.9, armor:.72, regen:4, eye:2.1, color:'#c3ca8d', gear:['warhammer','axe'], spells:['nova','ward','roots','heal'] }
};
export const WEAPONS = {
 sword: {name:'Wayfarer’s sword',family:'Sword',damage:24,range:3,cooldown:.58,price:45,kind:'melee',arc:.56,color:0xc2d2db,description:'A balanced steel blade with a broad, reliable cut.'},
 dagger: {name:'Moonfang dagger',family:'Dagger',damage:15,range:2.3,cooldown:.28,price:65,kind:'melee',arc:.7,color:0xa5decb,description:'A quick silver edge for close encounters.'},
 axe: {name:'Woodland battleaxe',family:'Axe',damage:39,range:3.1,cooldown:.92,price:125,kind:'melee',arc:.46,color:0xc9b38a,description:'Heavy chopping blows strike several nearby foes.'},
 mace: {name:'Dawnsteel mace',family:'Mace',damage:31,range:2.8,cooldown:.7,price:155,kind:'melee',arc:.7,stun:.8,color:0xe6ce84,description:'Crushing strikes briefly stagger an enemy.'},
 greatsword: {name:'Kingsguard greatsword',family:'Greatsword',damage:50,range:3.8,cooldown:1.15,price:260,kind:'melee',arc:.3,color:0xc1d5df,description:'Long, sweeping cuts punish groups of enemies.'},
 spear: {name:'Ashwood spear',family:'Spear',damage:29,range:5,cooldown:.75,price:130,kind:'melee',arc:.88,color:0xc1ced2,description:'Reach past your opponent’s guard with a precise thrust.'},
 warhammer: {name:'Stonebreaker',family:'Warhammer',damage:64,range:3.4,cooldown:1.45,price:310,kind:'melee',arc:.42,stun:1.1,color:0xaeb7a3,description:'An immense rune-cut hammer with a staggering impact.'},
 longbow: {name:'Moonwood longbow',family:'Bow',damage:30,range:60,cooldown:.75,price:165,kind:'ranged',speed:42,ammo:'arrows',color:0xa2d7b4,description:'A graceful bow with excellent reach. Uses arrows.'},
 crossbow: {name:'Ironhold crossbow',family:'Crossbow',damage:46,range:65,cooldown:1.25,price:240,kind:'ranged',speed:55,ammo:'bolts',color:0xd6c28f,description:'A slow, powerful ranged weapon. Uses bolts.'},
 chakram: {name:'Returning sunblade',family:'Chakram',damage:23,range:28,cooldown:.55,price:220,kind:'ranged',speed:28,color:0xffcc75,description:'An enchanted throwing ring that never consumes ammunition.'},
 emberstaff: {name:'Staff of embers',family:'Fire staff',damage:25,range:42,cooldown:.68,price:185,kind:'magic',speed:23,mana:4,color:0xff9450,description:'A carved staff that launches bolts of living flame.'},
 froststaff: {name:'Winterglass staff',family:'Ice staff',damage:21,range:48,cooldown:.62,price:225,kind:'magic',speed:30,mana:4,slow:2,color:0x91e4ff,description:'Frozen crystal bolts slow their target.'},
 wand: {name:'Starseeker wand',family:'Wand',damage:13,range:36,cooldown:.3,price:95,kind:'magic',speed:38,mana:2,color:0xc4a2ff,description:'Rapid arcane darts from a silver-tipped wand.'}
};
export const SPELLS = {
 fireball:{name:'Fireball',school:'Ember',glyph:'☀',cost:18,cooldown:2.5,damage:34,range:42,radius:3.8,speed:22,color:0xff8b43,description:'Hurl a blazing orb that explodes and burns enemies. Shatters chilled targets for 65% bonus impact damage.'},
 frost:{name:'Frost lance',school:'Winter',glyph:'❄',cost:14,cooldown:2,damage:27,range:45,speed:34,freeze:3,color:0x92ddff,description:'Launch an ice lance that freezes a foe. Follow with fire or lightning for an elemental combination.'},
 lightning:{name:'Chain lightning',school:'Storm',glyph:'ϟ',cost:27,cooldown:4,damage:31,range:25,color:0xb5c9ff,description:'Forked lightning leaps between four enemies. Chilled targets conduct 40% more damage.'},
 meteor:{name:'Starfall',school:'Celestial',glyph:'✷',cost:45,cooldown:10,damage:74,range:27,radius:6,color:0xffb276,description:'Call a blazing meteor into the targeting circle, scattering and burning nearby enemies.'},
 heal:{name:'Restoration',school:'Life',glyph:'✚',cost:24,cooldown:7,healing:48,color:0x89efb7,description:'Mend your wounds in a spiral of luminous leaves.'},
 ward:{name:'Arcane ward',school:'Protection',glyph:'◇',cost:22,cooldown:12,duration:9,shield:75,color:0x9baeff,description:'A translucent barrier absorbs damage for nine seconds.'},
 blink:{name:'Blink step',school:'Space',glyph:'»',cost:20,cooldown:5,range:9,color:0xcdb1ff,description:'Flash forward along a clear path. Walls and rivers still stop you.'},
 roots:{name:'Grasping roots',school:'Nature',glyph:'♧',cost:23,cooldown:7,damage:14,duration:5,radius:7,color:0xaad88b,description:'Roots erupt around you and bind nearby enemies.'},
 nova:{name:'Arcane nova',school:'Force',glyph:'✧',cost:30,cooldown:7,damage:40,radius:7,color:0xc5a0ff,description:'Release a ring of force that damages and pushes enemies away.'},
 wisp:{name:'Spirit companion',school:'Summoning',glyph:'◉',cost:35,cooldown:24,duration:18,damage:16,range:20,color:0x99f4e2,description:'Summon a friendly wisp that follows you and fires at your foes.'},
 blizzard:{name:'Winter’s veil',school:'Winter',glyph:'❅',cost:36,cooldown:12,duration:7,damage:9,range:20,radius:6,color:0xbbebff,description:'Summon a swirling snowstorm that damages, chills and slows enemies, preparing elemental combinations.'},
 haste:{name:'Windwalk',school:'Wind',glyph:'≋',cost:25,cooldown:18,duration:11,color:0xc3eab3,description:'Ride a tailwind to move much faster for eleven seconds.'}
};
export const ENEMY_DEFS={wolf:{name:'Briar wolf',health:52,damage:9,speed:2.8,xp:22,coin:9},goblin:{name:'Road goblin',health:72,damage:12,speed:2.2,xp:34,coin:15},skeleton:{name:'Hollow knight',health:92,damage:15,speed:1.9,xp:46,coin:21},wraith:{name:'Rift wraith',health:110,damage:17,speed:2.3,xp:58,coin:27},sentinel:{name:'Runestone guardian',health:260,damage:25,speed:1.5,xp:130,coin:75}};
export function freshHero(){return{version:1,archetype:null,level:1,xp:0,health:125,mana:85,weapons:['sword'],equipped:'sword',slots:['fireball','heal','ward','haste'],selected:0,arrows:40,bolts:25,potions:3,kills:0,defeated:{},cooldowns:{},effects:{},shield:0};}
export function stats(h){const a=ARCHETYPES[h.archetype]||ARCHETYPES.human;return{...a,health:a.health+(h.level-1)*9,mana:a.mana+(h.level-1)*7,power:1+(h.level-1)*.075};}
export const nextLevelXP=h=>h.level*75;
export function chooseArchetype(s,id){if(!Object.hasOwn(ARCHETYPES,id))return{ok:false,message:'Choose a character from the four available.'};const h=s.hero,first=h.archetype===null,old=stats(h),hpRatio=h.health/old.health,mpRatio=h.mana/old.mana;h.archetype=id;h.weapons=[...new Set([...h.weapons,...ARCHETYPES[id].gear])];h.equipped=ARCHETYPES[id].gear[0];h.slots=id==='wizard'?['fireball','frost','heal','blink']:ARCHETYPES[id].spells.slice(0,4);h.selected=0;const max=stats(h);h.health=first?max.health:Math.max(1,Math.min(max.health,hpRatio*max.health));h.mana=first?max.mana:Math.min(max.mana,mpRatio*max.mana);return{ok:true,message:ARCHETYPES[id].name+' · '+ARCHETYPES[id].title};}
export function buyWeapon(s,id){const w=Object.hasOwn(WEAPONS,id)?WEAPONS[id]:null;if(!w)return{ok:false,message:'Unknown weapon.'};if(s.hero.weapons.includes(id))return{ok:false,message:'You already own this weapon.'};if(s.coins<w.price)return{ok:false,message:'You need '+w.price+' coin.'};s.coins-=w.price;s.hero.weapons.push(id);s.hero.equipped=id;return{ok:true,message:w.name+' acquired and equipped.'};}
export function equipWeapon(s,id){if(!s.hero.weapons.includes(id)||!Object.hasOwn(WEAPONS,id))return{ok:false,message:'You do not own that weapon.'};s.hero.equipped=id;return{ok:true,message:WEAPONS[id].name+' equipped.'};}
export function assignSpell(s,slot,id){if(!Number.isInteger(slot)||slot<0||slot>3||!ARCHETYPES[s.hero.archetype]?.spells.includes(id))return{ok:false,message:'That spell is not available to this character.'};s.hero.slots[slot]=id;return{ok:true,message:SPELLS[id].name+' bound to key '+(slot+1)+'.'};}
export function spendCast(h,id){const p=SPELLS[id];if(!p||!ARCHETYPES[h.archetype]?.spells.includes(id))return{ok:false,message:'This character does not know that spell.'};if(h.health<=0)return{ok:false,message:'Recover before casting.'};if((h.cooldowns[id]||0)>0)return{ok:false,message:p.name+' is recharging.'};if(h.mana<p.cost)return{ok:false,message:'Not enough mana. It regenerates over time.'};if(id==='heal'&&h.health>=stats(h).health)return{ok:false,message:'You are already at full health.'};h.mana-=p.cost;h.cooldowns[id]=p.cooldown;return{ok:true};}
export function spendAttack(h){const w=WEAPONS[h.equipped];if(!w||!h.weapons.includes(h.equipped)||h.health<=0||(h.cooldowns.attack||0)>0)return{ok:false,message:''};if(w.ammo&&h[w.ammo]<=0)return{ok:false,message:'Out of '+w.ammo+'. Buy supplies from Rowan or Gareth.'};if(w.mana&&h.mana<w.mana)return{ok:false,message:'Not enough mana. Equip a blade while you recover.'};if(w.ammo)h[w.ammo]--;h.mana-=w.mana||0;h.cooldowns.attack=w.cooldown;return{ok:true,weapon:w};}
export function tickHero(h,dt){if(!Number.isFinite(dt)||dt<=0)return;for(const key of Object.keys(h.cooldowns))h.cooldowns[key]=Math.max(0,h.cooldowns[key]-dt);for(const key of Object.keys(h.effects))h.effects[key]=Math.max(0,h.effects[key]-dt);if(!h.effects.ward)h.shield=0;h.mana=Math.min(stats(h).mana,h.mana+stats(h).regen*dt);}
export function hurtHero(h,amount,blocking=false){if(!Number.isFinite(amount)||amount<=0||h.health<=0||h.effects.grace>0)return 0;let damage=amount*stats(h).armor*(blocking?.35:1);if(h.shield>0){const absorb=Math.min(h.shield,damage);h.shield-=absorb;damage-=absorb;}h.health=Math.max(0,h.health-damage);return damage;}
export function rewardKill(s,enemy){const h=s.hero;if(h.defeated[enemy.id]===s.day)return{rewarded:false,levels:0};h.defeated[enemy.id]=s.day;h.kills++;s.coins+=enemy.coin;h.xp+=enemy.xp;let levels=0;while(h.level<20&&h.xp>=nextLevelXP(h)){h.xp-=nextLevelXP(h);h.level++;levels++;}if(h.level===20)h.xp=Math.min(h.xp,nextLevelXP(h));if(levels){h.health=stats(h).health;h.mana=stats(h).mana;}return{rewarded:true,levels};}
export function recover(s){const fee=Math.min(30,Math.floor(s.coins*.1));s.coins-=fee;s.position={x:0,z:28,yaw:0,pitch:0};s.hero.health=stats(s.hero).health;s.hero.mana=stats(s.hero).mana;s.hero.shield=0;s.hero.effects={grace:8};return{ok:true,message:'Rescued at Eldermere · '+fee+' coin paid for your recovery.'};}
export function drinkPotion(s){if(s.hero.potions<1)return{ok:false,message:'No healing draughts left. Visit Rowan or Gareth.'};if(s.hero.health>=stats(s.hero).health)return{ok:false,message:'You are already at full health.'};s.hero.potions--;s.hero.health=Math.min(stats(s.hero).health,s.hero.health+65);return{ok:true,message:'Healing draught · restored up to 65 health.'};}
export function buySupply(s,id){const offers={arrows:{qty:30,cost:12},bolts:{qty:20,cost:15},potions:{qty:1,cost:25}};const offer=Object.hasOwn(offers,id)?offers[id]:null;if(!offer||s.coins<offer.cost)return{ok:false,message:'You do not have enough coin for those supplies.'};if(s.hero[id]+offer.qty>9999)return{ok:false,message:'You cannot carry more of that supply.'};s.coins-=offer.cost;s.hero[id]+=offer.qty;return{ok:true,message:'Purchased '+offer.qty+' '+id+'.'};}
export function validHero(h){const n=(v,a,b)=>typeof v==='number'&&Number.isFinite(v)&&v>=a&&v<=b,i=(v,a,b)=>Number.isSafeInteger(v)&&v>=a&&v<=b;if(!h||h.version!==1||(h.archetype!==null&&!Object.hasOwn(ARCHETYPES,h.archetype))||!i(h.level,1,20)||!i(h.xp,0,1500)||!n(h.health,0,stats(h).health)||!n(h.mana,0,stats(h).mana)||!i(h.kills,0,1e9)||!i(h.selected,0,3)||!n(h.shield,0,150))return false;if(!Array.isArray(h.weapons)||h.weapons.length<1||h.weapons.length>13||new Set(h.weapons).size!==h.weapons.length||!h.weapons.every(w=>Object.hasOwn(WEAPONS,w))||!h.weapons.includes(h.equipped))return false;const known=(ARCHETYPES[h.archetype]||ARCHETYPES.human).spells;if(!Array.isArray(h.slots)||h.slots.length!==4||!h.slots.every(p=>known.includes(p)))return false;for(const key of ['arrows','bolts','potions'])if(!i(h[key],0,9999))return false;if(!h.defeated||Array.isArray(h.defeated)||typeof h.defeated!=='object'||!Object.entries(h.defeated).every(([k,v])=>/^hostile-\d+$/.test(k)&&i(v,1,1e7)))return false;for(const field of ['cooldowns','effects']){if(!h[field]||Array.isArray(h[field])||typeof h[field]!=='object')return false;const allowed=field==='cooldowns'?['attack',...Object.keys(SPELLS)]:['ward','haste','wisp','grace'];if(!Object.entries(h[field]).every(([k,v])=>allowed.includes(k)&&n(v,0,60)))return false;}return true;}
