import {ARCHETYPES,WEAPONS,SPELLS,ENEMY_DEFS,stats,spendAttack,spendCast,tickHero,hurtHero,rewardKill,recover} from './rpg.js';
import {TOWNS,blocksAt,moveWithCollision,surfaceAt} from './world.js';
export const ENCOUNTERS=[
 {name:'Briarwood prowlers',x:-43,z:29,kinds:['wolf','wolf','wolf']},
 {name:'The broken caravan',x:-60,z:-19,kinds:['goblin','goblin','goblin']},
 {name:'Whispering stones',x:-64,z:-132,kinds:['skeleton','wraith','skeleton']},
 {name:'The eastern watch',x:104,z:26,kinds:['goblin','skeleton','wolf']},
 {name:'The fallen guardian',x:145,z:-133,kinds:['sentinel','wraith','skeleton']}
];
export const isSanctuary=p=>TOWNS.some(t=>Math.hypot(p.x-t.x,p.z-t.z)<32);
export function segmentEntry(a,b,colliders){const dx=b.x-a.x,dz=b.z-a.z;let earliest=Infinity;for(const c of colliders){let lo=0,hi=1,hit=true;for(const [v,d,min,max]of[[a.x,dx,c.x1,c.x2],[a.z,dz,c.z1,c.z2]]){if(Math.abs(d)<1e-9){if(v<min||v>max){hit=false;break;}}else{let t1=(min-v)/d,t2=(max-v)/d;if(t1>t2)[t1,t2]=[t2,t1];lo=Math.max(lo,t1);hi=Math.min(hi,t2);if(lo>hi){hit=false;break;}}}if(hit&&hi>0&&lo<1)earliest=Math.min(earliest,Math.max(0,lo));}return earliest;}
export const segmentBlocked=(a,b,colliders)=>segmentEntry(a,b,colliders)!==Infinity;
const distance=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
export function sphereEntry(center,a,b,radius){const x=a.x-center.x,y=a.y-center.y,z=a.z-center.z,dx=b.x-a.x,dy=b.y-a.y,dz=b.z-a.z;const aa=dx*dx+dy*dy+dz*dz,bb=2*(x*dx+y*dy+z*dz),cc=x*x+y*y+z*z-radius*radius;if(cc<=0)return 0;if(aa<1e-12)return Infinity;const disc=bb*bb-4*aa*cc;if(disc<0)return Infinity;const t=(-bb-Math.sqrt(disc))/(2*aa);return t>=0&&t<=1?t:Infinity;}

export function createCombat({state,world,emit=()=>{},notify=()=>{},changed=()=>{},onDefeat=()=>{}}){
 const enemies=[],projectiles=[],zones=[];let clock=0,day=state().day,held=false,blocking=false,wispTimer=0;
 function spawn(){enemies.length=0;let index=0;for(const camp of ENCOUNTERS)camp.kinds.forEach((kind,i)=>{let x=camp.x+Math.cos(i*2.4)*3,z=camp.z+Math.sin(i*2.4)*3;for(let j=0;j<40&&blocksAt(x,z,world.colliders,.35);j++){x=camp.x+Math.cos(j*1.7)*(3+j*.22);z=camp.z+Math.sin(j*1.7)*(3+j*.22);}const d=ENEMY_DEFS[kind];enemies.push({id:'hostile-'+index++,kind,...d,maxHealth:d.health,x,z,homeX:x,homeZ:z,heading:0,dead:state().hero.defeated['hostile-'+(index-1)]===day,freeze:0,slow:0,attackTime:1,flash:0});});}
 function clear(){projectiles.length=0;zones.length=0;held=blocking=false;wispTimer=0;emit({type:'clear'});}
 function damage(e,amount,color=0xffdb99,status={}){if(e.dead||e.health<=0||isSanctuary(e))return false;e.health=Math.max(0,e.health-amount);e.flash=.14;e.freeze=Math.max(e.freeze,status.freeze||0);e.slow=Math.max(e.slow,status.slow||0);emit({type:'hit',x:e.x,y:surfaceAt(e.x,e.z)+1.2,z:e.z,color,amount:Math.round(amount)});if(e.health===0){e.dead=true;const result=rewardKill(state(),e);if(result.rewarded){notify(result.levels?'Level '+state().hero.level+' · health and mana restored':e.name+' defeated · +'+e.coin+' coin · +'+e.xp+' XP');emit({type:'burst',x:e.x,y:1,z:e.z,color:0xfad58b,radius:1.3});changed();}}return true;}
 function area(center,radius,amount,color,status={}){for(const e of enemies)if(!e.dead&&(Number.isFinite(center.y)?Math.hypot(e.x-center.x,e.z-center.z,surfaceAt(e.x,e.z)+1.1-center.y):distance(e,center))<=radius&&!segmentBlocked(center,e,world.colliders)){damage(e,amount,color,status);if(status.push){const d=Math.max(.1,distance(e,center));moveWithCollision(e,(e.x-center.x)/d*status.push,(e.z-center.z)/d*status.push,world.colliders,.3);}}}
 function launch(origin,direction,data){projectiles.push({x:origin.x,y:origin.y,z:origin.z,dx:direction.x,dy:direction.y,dz:direction.z,speed:data.speed||25,life:(data.range||40)/(data.speed||25),...data,id:Math.random()});}
 function facingTarget(range,threshold=.7){const p=state().position,fx=-Math.sin(p.yaw),fz=-Math.cos(p.yaw);return enemies.filter(e=>!e.dead&&distance(e,p)<range&&((e.x-p.x)*fx+(e.z-p.z)*fz)/Math.max(.01,distance(e,p))>threshold&&!segmentBlocked(p,e,world.colliders)).sort((a,b)=>distance(a,p)-distance(b,p))[0];}
 function groundTarget(range){const p=state().position,eye=stats(state().hero).eye;const d=p.pitch<-.08?Math.min(range,-eye/Math.tan(p.pitch)):range;const result={x:p.x,z:p.z};moveWithCollision(result,-Math.sin(p.yaw)*d,-Math.cos(p.yaw)*d,world.colliders,.15);return result;}
 function attack(){const s=state(),h=s.hero,result=spendAttack(h);if(!result.ok){if(result.message){held=false;notify(result.message);}return result;}const w=result.weapon,p=s.position,a=stats(h),damageAmount=w.damage*a.power*(w.kind==='melee'?a.melee:w.kind==='magic'?a.magic:a.ranged);emit({type:'swing',weapon:h.equipped,color:w.color});if(w.kind==='melee'){const targets=enemies.filter(e=>!e.dead&&distance(e,p)<=w.range&&((e.x-p.x)*-Math.sin(p.yaw)+(e.z-p.z)*-Math.cos(p.yaw))/Math.max(.01,distance(e,p))>w.arc&&!segmentBlocked(p,e,world.colliders));for(const e of targets)damage(e,damageAmount,w.color,{freeze:w.stun||0});if(h.equipped==='warhammer')emit({type:'ring',...groundTarget(2),y:.13,radius:2,color:w.color,duration:.35});}else{const cp=Math.cos(p.pitch);launch({x:p.x,y:surfaceAt(p.x,p.z)+a.eye-.12,z:p.z},{x:-Math.sin(p.yaw)*cp,y:Math.sin(p.pitch),z:-Math.cos(p.yaw)*cp},{speed:w.speed,range:w.range,damage:damageAmount,color:w.color,slow:w.slow||0,weapon:h.equipped});}changed();return{ok:true};}
 function cast(slot){const s=state(),h=s.hero;if(!Number.isInteger(slot)||slot<0||slot>3)return{ok:false,message:'Choose a spell slot.'};const id=h.slots[slot],p=SPELLS[id],result=spendCast(h,id);if(!result.ok){notify(result.message);return result;}h.selected=slot;const pos=s.position,a=stats(h),power=a.power*a.magic;emit({type:'cast',spell:id,color:p.color});
  if(id==='heal'){h.health=Math.min(a.health,h.health+p.healing*power);emit({type:'ring',x:pos.x,y:surfaceAt(pos.x,pos.z)+.2,z:pos.z,radius:2,color:p.color,duration:1.5});}
  else if(id==='ward'){h.effects.ward=p.duration;h.shield=p.shield;}
  else if(id==='haste')h.effects.haste=p.duration;
  else if(id==='wisp'){h.effects.wisp=p.duration;wispTimer=0;}
  else if(id==='blink'){const old={...pos};moveWithCollision(pos,-Math.sin(pos.yaw)*p.range,-Math.cos(pos.yaw)*p.range,world.colliders);emit({type:'burst',x:old.x,y:surfaceAt(old.x,old.z)+1,z:old.z,color:p.color,radius:1});emit({type:'burst',x:pos.x,y:surfaceAt(pos.x,pos.z)+1,z:pos.z,color:p.color,radius:1});}
  else if(id==='fireball'||id==='frost'){const cp=Math.cos(pos.pitch);launch({x:pos.x,y:surfaceAt(pos.x,pos.z)+a.eye-.1,z:pos.z},{x:-Math.sin(pos.yaw)*cp,y:Math.sin(pos.pitch),z:-Math.cos(pos.yaw)*cp},{speed:p.speed,range:p.range,damage:p.damage*power,radius:p.radius||0,freeze:p.freeze||0,color:p.color,spell:id});}
  else if(id==='lightning'){let target=facingTarget(p.range,.45),from={x:pos.x,y:surfaceAt(pos.x,pos.z)+a.eye,z:pos.z};const seen=new Set();for(let i=0;i<4&&target;i++){seen.add(target.id);emit({type:'lightning',from,to:{x:target.x,y:surfaceAt(target.x,target.z)+1.1,z:target.z},color:p.color});damage(target,p.damage*power*(1-i*.12),p.color,{freeze:.35});from={x:target.x,y:surfaceAt(target.x,target.z)+1,z:target.z};target=enemies.filter(e=>!e.dead&&!seen.has(e.id)&&distance(e,from)<7&&!segmentBlocked(from,e,world.colliders)).sort((a,b)=>distance(a,from)-distance(b,from))[0];}if(!seen.size)emit({type:'lightning',from,to:{...groundTarget(14),y:.3},color:p.color});}
  else if(id==='nova'||id==='roots'){area(pos,p.radius,p.damage*power,p.color,id==='roots'?{freeze:p.duration}:{push:3});emit({type:id==='roots'?'roots':'ring',x:pos.x,y:surfaceAt(pos.x,pos.z)+.15,z:pos.z,radius:p.radius,color:p.color,duration:id==='roots'?2:.75});}
  else if(id==='meteor'){const target=groundTarget(p.range);zones.push({...target,id,delay:.8,remaining:.8,radius:p.radius,damage:p.damage*power,color:p.color});emit({type:'meteor',...target,y:surfaceAt(target.x,target.z),color:p.color,radius:p.radius,duration:.8});}
  else if(id==='blizzard'){const target=groundTarget(p.range);zones.push({...target,id,remaining:p.duration,tick:0,radius:p.radius,damage:p.damage*power,color:p.color});emit({type:'blizzard',...target,y:surfaceAt(target.x,target.z),color:p.color,radius:p.radius,duration:p.duration});}
  changed();return{ok:true,message:p.name};
 }
 function update(dt){if(!Number.isFinite(dt)||dt<=0)return;dt=Math.min(dt,.1);clock+=dt;const s=state(),h=s.hero;if(day!==s.day){day=s.day;clear();spawn();}tickHero(h,dt);if(held)attack();const safe=isSanctuary(s.position);
  for(const e of enemies){if(e.dead)continue;e.freeze=Math.max(0,e.freeze-dt);e.slow=Math.max(0,e.slow-dt);e.flash=Math.max(0,e.flash-dt);e.attackTime=Math.max(0,e.attackTime-dt);const d=distance(e,s.position),chase=!safe&&d<21&&distance(e,{x:e.homeX,z:e.homeZ})<32;let dest=chase?s.position:{x:e.homeX+Math.cos(clock*.15+Number(e.id.slice(8)))*2,z:e.homeZ+Math.sin(clock*.15+Number(e.id.slice(8)))*2};if(e.freeze===0&&distance(e,dest)>1.7){const heading=Math.atan2(dest.x-e.x,dest.z-e.z),step=e.speed*(e.slow?.35:1)*dt;const next={x:e.x,z:e.z};moveWithCollision(next,Math.sin(heading)*step,Math.cos(heading)*step,world.colliders,.34);if(!isSanctuary(next)){e.x=next.x;e.z=next.z;}e.heading=heading;}
   if(chase&&d<2.25&&e.freeze===0&&e.attackTime<=0&&!segmentBlocked(e,s.position,world.colliders)){e.attackTime=e.kind==='sentinel'?1.8:1.2;const amount=hurtHero(h,e.damage,blocking);emit({type:'hurt',amount});if(h.health===0){const result=recover(s);clear();notify(result.message);onDefeat();changed();break;}}
  }
  for(let i=projectiles.length-1;i>=0;i--){const p=projectiles[i],old={x:p.x,y:p.y,z:p.z},step=Math.min(dt,Math.max(0,p.life));const end={x:p.x+p.dx*p.speed*step,y:p.y+p.dy*p.speed*step,z:p.z+p.dz*p.speed*step};p.life-=dt;let hit=null,hitT=Infinity;
   for(const e of enemies){if(e.dead)continue;const center={x:e.x,y:surfaceAt(e.x,e.z)+(e.kind==='wolf'?.85:e.kind==='sentinel'?1.6:1.1),z:e.z};const t=sphereEntry(center,old,end,e.kind==='sentinel'?1:.7);if(t<hitT){hitT=t;hit=e;}}
   const wallT=segmentEntry(old,end,world.colliders);const floor=surfaceAt(end.x,end.z)+.07,groundT=end.y<floor?Math.max(0,Math.min(1,(old.y-floor)/(old.y-end.y||1))):Infinity;const impactT=Math.min(hitT,wallT,groundT);
   const fraction=impactT===Infinity?1:Math.max(0,impactT-.0005);p.x=old.x+(end.x-old.x)*fraction;p.y=old.y+(end.y-old.y)*fraction;p.z=old.z+(end.z-old.z)*fraction;
   if(impactT!==Infinity||p.life<=0){if(p.radius)area(p,p.radius,p.damage,p.color);else if(hit&&hitT<=wallT&&hitT<=groundT)damage(hit,p.damage,p.color,{freeze:p.freeze,slow:p.slow});emit({type:'burst',x:p.x,y:Math.max(.1,p.y),z:p.z,color:p.color,radius:p.radius||.45});projectiles.splice(i,1);}
  }
  for(let i=zones.length-1;i>=0;i--){const zone=zones[i];zone.remaining-=dt;if(zone.id==='meteor'&&zone.remaining<=0){area(zone,zone.radius,zone.damage,zone.color,{push:1.5});emit({type:'burst',...zone,y:surfaceAt(zone.x,zone.z)+.4,radius:zone.radius});zones.splice(i,1);}else if(zone.id==='blizzard'){zone.tick-=dt;if(zone.tick<=0){zone.tick=.7;area(zone,zone.radius,zone.damage,zone.color,{slow:1.2});}if(zone.remaining<=0)zones.splice(i,1);}}
  if(h.effects.wisp>0){wispTimer-=dt;if(wispTimer<=0){wispTimer=1.25;const target=enemies.filter(e=>!e.dead&&distance(e,s.position)<20&&!segmentBlocked(s.position,e,world.colliders)).sort((a,b)=>distance(a,s.position)-distance(b,s.position))[0];if(target){emit({type:'lightning',from:{x:s.position.x+1,y:surfaceAt(s.position.x,s.position.z)+2.2,z:s.position.z},to:{x:target.x,y:surfaceAt(target.x,target.z)+1,z:target.z},color:SPELLS.wisp.color});damage(target,SPELLS.wisp.damage*stats(h).magic,SPELLS.wisp.color);}}}
 }
 spawn();return{enemies,projectiles,zones,attack,cast,update,clear,reset(){clear();day=state().day;spawn();},setHeld(value){held=value;},setBlocking(value){blocking=value;},get blocking(){return blocking;},target(){return facingTarget(30,.96);},get clock(){return clock;}};
}
