import * as T from '../vendor/three.module.js';
import {surfaceAt} from './world.js';
import {TRAINING} from './combat.js';
import {createSpellEffects} from './spell-effects.js';
import {weaponModel,enemyModel,mat,orb,rod,cube,beam,disposeModel} from './models.js';
export function loadWorldTextures(renderer){const loader=new T.TextureLoader();const textures={};for(const [key,file]of Object.entries({grass:'forest-floor.png',stone:'cobblestone.png',wood:'oak-planks.png'})){const texture=loader.load(new URL('../assets/'+file,import.meta.url).href,undefined,undefined,()=>{});texture.colorSpace=T.SRGBColorSpace;texture.wrapS=texture.wrapT=T.RepeatWrapping;texture.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());textures[key]=texture;}return textures;}
export function createAtmosphere(scene){
 const uniforms={time:{value:0},day:{value:1},sun:{value:new T.Vector3(-.5,.65,.4).normalize()}};
 const sky=new T.Mesh(new T.SphereGeometry(460,36,20),new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms,vertexShader:'varying vec3 vSky; void main(){vSky=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`varying vec3 vSky; uniform float time; uniform float day; uniform vec3 sun;
float noise(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float smoothnoise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(noise(i),noise(i+vec2(1,0)),f.x),mix(noise(i+vec2(0,1)),noise(i+vec2(1,1)),f.x),f.y);}float fbm(vec2 p){return smoothnoise(p)*.55+smoothnoise(p*2.1)*.27+smoothnoise(p*4.2)*.13+smoothnoise(p*8.1)*.05;}
void main(){vec3 d=normalize(vSky);float h=max(d.y,0.);vec3 noon=mix(vec3(.72,.81,.76),vec3(.23,.46,.61),pow(h,.52));vec3 night=mix(vec3(.08,.13,.20),vec3(.012,.024,.065),pow(h,.5));vec3 color=mix(night,noon,day);float sd=max(dot(d,sun),0.);color+=vec3(1.,.8,.5)*(pow(sd,650.)*2.+pow(sd,16.)*.18)*day;vec2 uv=d.xz/max(.16,d.y)*1.9+vec2(time*.009,0.);float cloud=smoothstep(.5,.7,fbm(uv))*smoothstep(.03,.23,d.y);color=mix(color,mix(vec3(.16,.2,.28),vec3(.95,.93,.82),day),cloud*.78);float stars=step(.998,noise(floor(d.xz/max(.12,d.y)*300.)))*smoothstep(.1,.3,d.y);color+=stars*(1.-day)*.8;gl_FragColor=vec4(color,1.);}` }));sky.renderOrder=-10;sky.frustumCulled=false;scene.add(sky);
 const waterUniforms={time:{value:0},day:{value:1}};
 const water=new T.Mesh(new T.PlaneGeometry(11.7,430,16,180),new T.ShaderMaterial({transparent:true,depthWrite:false,uniforms:waterUniforms,vertexShader:`varying vec2 vUV; varying vec3 vWorld; uniform float time; void main(){vUV=uv; vec3 p=position;p.z+=sin(p.x*1.7+time*1.2)*.025+sin(p.y*.4+time)*.018;vec4 w=modelMatrix*vec4(p,1.);vWorld=w.xyz;gl_Position=projectionMatrix*viewMatrix*w;}`,fragmentShader:`varying vec2 vUV;varying vec3 vWorld;uniform float time;uniform float day;void main(){float wave=sin(vUV.x*140.+sin(vUV.y*70.+time)*2.+time*1.4)*sin(vUV.y*1100.-time*3.);float foam=smoothstep(.73,1.,wave)*.16;float edge=pow(abs(vUV.x-.5)*2.,18.);vec3 color=mix(vec3(.09,.27,.28),vec3(.27,.51,.48),vUV.x);color+=foam+edge*.12;vec3 view=normalize(cameraPosition-vWorld);float fresnel=pow(1.-abs(view.y),3.);color=mix(color,vec3(.57,.74,.78),fresnel*.65);gl_FragColor=vec4(color*(.25+day*.8),.94);}` }));water.rotation.x=-Math.PI/2;water.position.set(56,.06,0);scene.add(water);
 // Warm pools of light at doors make interiors legible without a light per prop.
 const lanterns=[];for(const [x,z]of [[-7,13],[7,13],[-11,-15],[11,-14],[-111,-93],[97,-120]]){const light=new T.PointLight(0xffc780,5,13,2);light.position.set(x,2.4,z);scene.add(light);lanterns.push(light);}
 return{update(time,day,position){uniforms.time.value=time;uniforms.day.value=day;waterUniforms.time.value=time;waterUniforms.day.value=day;sky.position.set(position.x,0,position.z);for(const l of lanterns)l.intensity=(1.5+(1-day)*6)*(1+Math.sin(time*4+l.position.x)*.05);},sky};
}
export function createCombatGraphics(scene,camera,state,settings){
 const group=new T.Group();scene.add(group);const enemyMeshes=new Map(),fx=createSpellEffects(scene,settings);let heldId='',heldClass='',heldModel=null,swing=0,castFlash=0,hurt=0,wardHit=0,ambient=0;
 const hands=new T.Group();camera.add(hands);scene.add(camera);hands.position.set(.36,-.4,-.66);const offhand=new T.Group();offhand.position.set(-.32,-.35,-.55);camera.add(offhand);const glow=orb(offhand,mat(0xb9a2ff,.1,2),0,.11,-.1,.035),handLight=new T.PointLight(0xc4a2ff,0,3);offhand.add(handLight);
 const castSeal=new T.Group();offhand.add(castSeal);castSeal.position.set(0,.13,-.14);const sealMaterial=new T.MeshBasicMaterial({color:0xcab7ff,transparent:true,opacity:.6,side:T.DoubleSide,blending:T.AdditiveBlending,depthWrite:false});for(const r of [.11,.145])castSeal.add(new T.Mesh(new T.TorusGeometry(r,.004,4,40),sealMaterial));for(let i=0;i<6;i++){const a=i/6*Math.PI*2,m=new T.Mesh(new T.OctahedronGeometry(.012),sealMaterial);m.position.set(Math.cos(a)*.13,Math.sin(a)*.13,0);castSeal.add(m);}
 const wardMaterial=new T.ShaderMaterial({transparent:true,side:T.DoubleSide,depthWrite:false,blending:T.AdditiveBlending,uniforms:{time:{value:0},impact:{value:0}},vertexShader:`varying vec3 vNormal;varying vec3 vView;varying vec2 vUV;void main(){vec4 v=modelViewMatrix*vec4(position,1.);vNormal=normalize(normalMatrix*normal);vView=normalize(-v.xyz);vUV=uv;gl_Position=projectionMatrix*v;}`,fragmentShader:`varying vec3 vNormal;varying vec3 vView;varying vec2 vUV;uniform float time;uniform float impact;void main(){float rim=pow(1.-abs(dot(normalize(vNormal),normalize(vView))),2.);vec2 grid=vUV*vec2(24.,12.);float cells=pow(abs(sin(grid.x*3.14159)*sin(grid.y*3.14159)),14.);float sweep=pow(.5+.5*sin(vUV.y*30.-time*3.),12.);float a=.025+rim*.13+cells*.08+sweep*.025+impact*.13;gl_FragColor=vec4(vec3(.43,.65,1.5),a);}`});const ward=new T.Mesh(new T.SphereGeometry(1.25,36,24),wardMaterial);scene.add(ward);
 const wisp=new T.Group();orb(wisp,mat(0x9cf4df,0,3),0,0,0,.11);for(let i=0;i<2;i++){const halo=new T.Mesh(new T.TorusGeometry(.2+i*.07,.012,5,32),new T.MeshBasicMaterial({color:0x9cf8e6,transparent:true,opacity:.6,blending:T.AdditiveBlending,depthWrite:false}));halo.rotation.x=i*Math.PI/2;wisp.add(halo);}scene.add(wisp);
 const aim=new T.Mesh(new T.RingGeometry(.96,1,64),new T.MeshBasicMaterial({color:0xaddfff,transparent:true,opacity:.38,side:T.DoubleSide,depthWrite:false}));aim.rotation.x=-Math.PI/2;scene.add(aim);
 const statusCrystal=new T.OctahedronGeometry(1),statusSphere=new T.SphereGeometry(1,10,8),statusRing=new T.TorusGeometry(.52,.05,5,20);
 const frostMat=new T.MeshBasicMaterial({color:0x9adcff,transparent:true,opacity:.3,depthWrite:false}),rootMat=new T.MeshStandardMaterial({color:0x638945,roughness:.9});
 // A safe practice space beside the southern Eldermere road.
 const practice=new T.Group();practice.position.set(TRAINING.x,surfaceAt(TRAINING.x,TRAINING.z)+.035,TRAINING.z);scene.add(practice);
 const ring=new T.Mesh(new T.TorusGeometry(4.7,.045,5,64),new T.MeshStandardMaterial({color:0xa3c6d0,emissive:0x74bfd0,emissiveIntensity:.35}));ring.rotation.x=-Math.PI/2;practice.add(ring);for(let i=0;i<12;i++){const a=i/12*Math.PI*2;const stone=cube(practice,0x748080,Math.cos(a)*4.7,.1,Math.sin(a)*4.7,.3,.2,.3);stone.rotation.y=a;}
 const focus=new T.Group();focus.position.set(TRAINING.focus.x,surfaceAt(TRAINING.focus.x,TRAINING.focus.z),TRAINING.focus.z);scene.add(focus);rod(focus,0x667977,0,.38,0,.35,.76);const focusGem=new T.Mesh(new T.OctahedronGeometry(.25),mat(0xa6dfff,.25,1.8));focusGem.position.y=1.12;focus.add(focusGem);
 const cv=document.createElement('canvas');cv.width=768;cv.height=256;const ctx=cv.getContext('2d');ctx.fillStyle='#172d38';ctx.fillRect(0,0,768,256);ctx.strokeStyle='#a2c8d6';ctx.lineWidth=5;ctx.strokeRect(8,8,752,240);ctx.textAlign='center';ctx.fillStyle='#e2e6d5';ctx.font='42px Georgia';ctx.fillText('ARCANE PRACTICE',384,79);ctx.font='28px sans-serif';ctx.fillText('Strike the targets · try spell combinations',384,134);ctx.fillStyle='#a6dfff';ctx.fillText('E at the blue stone: restore mana & spells',384,190);const tex=new T.CanvasTexture(cv);tex.colorSpace=T.SRGBColorSpace;const sign=new T.Mesh(new T.PlaneGeometry(3.1,1.03),new T.MeshBasicMaterial({map:tex,side:T.DoubleSide}));sign.position.set(TRAINING.x,surfaceAt(TRAINING.x,TRAINING.z)+2.5,TRAINING.z-4.5);scene.add(sign);
 function emit(e){fx.emit(e);if(e.type==='swing')swing=1;if(e.type==='cast'){castFlash=1;glow.material=mat(e.color,0,2);handLight.color.setHex(e.color);sealMaterial.color.setHex(e.color);}if(e.type==='hurt'&&e.amount>0)hurt=.5;if(e.type==='guard')wardHit=1;if(e.type==='clear'){swing=castFlash=hurt=wardHit=0;}}
 function refreshWeapon(){const h=state().hero;if(heldId===h.equipped&&heldClass===h.archetype)return;heldId=h.equipped;heldClass=h.archetype;if(heldModel)disposeModel(heldModel);for(const child of [...hands.children])child.removeFromParent();heldModel=weaponModel(h.equipped);heldModel.scale.setScalar(h.equipped==='crossbow'?.7:.48);hands.add(heldModel);const skin=h.archetype==='ogre'?0x8b9d64:0xc59e7a;orb(heldModel,skin,0,.05,.04,.075,.1,.055);rod(heldModel,h.archetype==='wizard'?0x564378:0x484b40,0,-.1,.05,.067,.18);heldModel.traverse(o=>{if(o.isMesh)o.castShadow=false;});offhand.children.filter(c=>c.userData.hand).forEach(c=>c.removeFromParent());const hand=orb(offhand,skin,0,0,0,.057,.09,.045);hand.userData.hand=true;}
 function syncEnemies(enemies,time,paused){const ids=new Set(enemies.map(e=>e.id));for(const [id,g]of enemyMeshes)if(!ids.has(id)){for(const key of ['ice','roots','flash'])g.userData[key].removeFromParent();g.userData.flash.material.dispose();disposeModel(g);enemyMeshes.delete(id);}for(const e of enemies){let g=enemyMeshes.get(e.id);if(!g){g=enemyModel(e.kind);group.add(g);const status=new T.Group();g.add(status);for(let i=0;i<5;i++){const a=i*2.4,m=new T.Mesh(statusCrystal,frostMat);m.position.set(Math.cos(a)*.45,.25,Math.sin(a)*.45);m.scale.set(.1,.5,.1);status.add(m);}const roots=new T.Mesh(statusRing,rootMat);roots.rotation.x=Math.PI/2;roots.position.y=.35;g.add(roots);const flash=new T.Mesh(statusSphere,new T.MeshBasicMaterial({color:0xffdfb5,transparent:true,opacity:0,depthWrite:false,blending:T.AdditiveBlending}));flash.position.y=1.1;flash.scale.set(.52,.85,.5);g.add(flash);g.userData.ice=status;g.userData.roots=roots;g.userData.flash=flash;enemyMeshes.set(e.id,g);}g.visible=!e.dead;g.userData.ice.visible=e.chill>0||e.iceLock>0;g.userData.roots.visible=e.bind>0;g.userData.flash.material.opacity=(e.flash||0)*2;const moved=!paused&&Math.hypot(g.position.x-e.x,g.position.z-e.z)>.002;for(let i=0;i<(g.userData.legs||[]).length;i++)g.userData.legs[i].rotation.x=moved?Math.sin(time*9+i*Math.PI)*.32:0;for(let i=0;i<(g.userData.arms||[]).length;i++)g.userData.arms[i].rotation.x=e.windup>0?-.6-Math.sin((1-e.windup/e.windupTotal)*Math.PI/2)*1.1:moved?Math.sin(time*9+i*Math.PI)*.2:0;g.position.set(e.x,surfaceAt(e.x,e.z),e.z);g.rotation.y=e.heading;if(e.kind==='wraith')g.position.y+=.14+Math.sin(e.x+time*2)*.12;}}
 function update(dt,time,combat,playing,paused,moving){const h=state().hero,p=state().position,tick=paused?0:dt;refreshWeapon();hands.visible=offhand.visible=playing&&!paused;swing=Math.max(0,swing-tick*3.6);castFlash=Math.max(0,castFlash-tick*2.2);hurt=Math.max(0,hurt-tick);wardHit=Math.max(0,wardHit-tick*3);const t=Math.sin(swing*Math.PI);hands.rotation.set(-t*1.1,0,-.18-t*.8);hands.position.set(combat.blocking?.02:.36,-.4+t*.05+(!settings.reducedMotion&&moving?Math.sin(time*8)*.008:0),-.66);offhand.rotation.z=castFlash*.5;glow.scale.setScalar(1+castFlash*4);handLight.intensity=castFlash*3;castSeal.visible=castFlash>0;castSeal.scale.setScalar(.6+castFlash);castSeal.rotation.z=time*2;sealMaterial.opacity=castFlash*.8;
  ward.visible=playing&&h.effects.ward>0&&h.shield>0;ward.position.set(p.x,surfaceAt(p.x,p.z)+1,p.z);wardMaterial.uniforms.time.value=time;wardMaterial.uniforms.impact.value=wardHit;
  wisp.visible=playing&&h.effects.wisp>0;wisp.position.set(p.x+Math.cos(time*1.4),surfaceAt(p.x,p.z)+2.2+Math.sin(time*2)*.2,p.z+Math.sin(time*1.4));wisp.rotation.y=time;wisp.rotation.z=Math.sin(time)*.2;
  const target=playing&&!paused?combat.aim():null;aim.visible=!!target;if(target){aim.position.set(target.x,target.y,target.z);aim.scale.setScalar(target.radius);aim.material.color.setHex(target.color);aim.material.opacity=.22+Math.sin(time*3)*.08;}
  focusGem.rotation.y=time*.5;focusGem.position.y=1.12+Math.sin(time*2)*.05;ambient+=tick;if(ambient>.1){ambient=0;if(wisp.visible)fx.particle(wisp.position,0x98f8e3,{life:.9,size:.17,vy:.3});if(h.effects.haste>0&&moving)for(let i=0;i<4;i++)fx.particle({x:p.x+(Math.random()-.5)*1.5,y:surfaceAt(p.x,p.z)+Math.random(),z:p.z+(Math.random()-.5)*1.5},0xc3ebbf,{life:.5,size:.16,vy:.7});}
  const overlay=document.querySelector('#damage-overlay');if(overlay)overlay.style.opacity=String(hurt*.7);syncEnemies(combat.enemies,time,paused);fx.update(tick,combat,playing);
 }
 return{emit,update,refreshWeapon,enemyMeshes,fx};
}
