import * as T from '../vendor/three.module.js';
import {surfaceAt} from './world.js';
import {ARCHETYPES,WEAPONS,stats} from './rpg.js';
import {weaponModel,enemyModel,mat,orb,rod,cube,beam,disposeModel} from './models.js';
export function loadWorldTextures(renderer){const loader=new T.TextureLoader();const textures={};for(const [key,file]of Object.entries({grass:'forest-floor.png',stone:'cobblestone.png',wood:'oak-planks.png'})){const texture=loader.load(new URL('../assets/'+file,import.meta.url).href,undefined,undefined,()=>{});texture.colorSpace=T.SRGBColorSpace;texture.wrapS=texture.wrapT=T.RepeatWrapping;texture.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());textures[key]=texture;}return textures;}
export function createAtmosphere(scene){
 const uniforms={time:{value:0},day:{value:1},sun:{value:new T.Vector3(-.5,.65,.4).normalize()}};
 const sky=new T.Mesh(new T.SphereGeometry(460,36,20),new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms,vertexShader:'varying vec3 vSky; void main(){vSky=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`varying vec3 vSky; uniform float time; uniform float day; uniform vec3 sun;
float noise(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float smoothnoise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(noise(i),noise(i+vec2(1,0)),f.x),mix(noise(i+vec2(0,1)),noise(i+vec2(1,1)),f.x),f.y);}float fbm(vec2 p){return smoothnoise(p)*.55+smoothnoise(p*2.1)*.27+smoothnoise(p*4.2)*.13+smoothnoise(p*8.1)*.05;}
void main(){vec3 d=normalize(vSky);float h=max(d.y,0.);vec3 noon=mix(vec3(.72,.81,.76),vec3(.23,.46,.61),pow(h,.52));vec3 night=mix(vec3(.08,.13,.20),vec3(.012,.024,.065),pow(h,.5));vec3 color=mix(night,noon,day);float sd=max(dot(d,sun),0.);color+=vec3(1.,.8,.5)*(pow(sd,650.)*2.+pow(sd,16.)*.18)*day;vec2 uv=d.xz/max(.16,d.y)*1.9+vec2(time*.009,0.);float cloud=smoothstep(.5,.7,fbm(uv))*smoothstep(.03,.23,d.y);color=mix(color,mix(vec3(.16,.2,.28),vec3(.95,.93,.82),day),cloud*.78);float stars=step(.998,noise(floor(d.xz/max(.12,d.y)*300.)))*smoothstep(.1,.3,d.y);color+=stars*(1.-day)*.8;gl_FragColor=vec4(color,1.);}` }));sky.renderOrder=-10;sky.frustumCulled=false;scene.add(sky);
 const waterUniforms={time:{value:0},day:{value:1}};
 const water=new T.Mesh(new T.PlaneGeometry(11.7,430,16,180),new T.ShaderMaterial({transparent:true,depthWrite:false,uniforms:waterUniforms,vertexShader:`varying vec2 vUV; varying vec3 vWorld; uniform float time; void main(){vUV=uv; vec3 p=position;p.z+=sin(p.x*1.7+time*1.2)*.025+sin(p.y*.4+time)*.018;vec4 w=modelMatrix*vec4(p,1.);vWorld=w.xyz;gl_Position=projectionMatrix*viewMatrix*w;}`,fragmentShader:`varying vec2 vUV;varying vec3 vWorld;uniform float time;uniform float day;void main(){float wave=sin(vUV.x*140.+sin(vUV.y*70.+time)*2.+time*1.4)*sin(vUV.y*1100.-time*3.);float foam=smoothstep(.73,1.,wave)*.16;float edge=pow(abs(vUV.x-.5)*2.,18.);vec3 color=mix(vec3(.09,.27,.28),vec3(.27,.51,.48),vUV.x);color+=foam+edge*.12;vec3 view=normalize(cameraPosition-vWorld);float fresnel=pow(1.-abs(view.y),3.);color=mix(color,vec3(.57,.74,.78),fresnel*.65);gl_FragColor=vec4(color*(.25+day*.8),.94);}` }));water.rotation.x=-Math.PI/2;water.position.set(56,.06,0);scene.add(water);
 // Warm pools of light at doors make interiors legible without a light per prop.
 const lanterns=[];for(const [x,z]of [[-7,13],[7,13],[-11,-15],[11,-14],[-111,-93],[97,-120]]){const light=new T.PointLight(0xffc780,5,13,2);light.position.set(x,2.4,z);scene.add(light);lanterns.push(light);}
 return{update(time,day,position){uniforms.time.value=time;uniforms.day.value=day;waterUniforms.time.value=time;waterUniforms.day.value=day;sky.position.set(position.x,0,position.z);for(const l of lanterns)l.intensity=(1.5+(1-day)*6)*(1+Math.sin(time*4+l.position.x)*.05);},sky};
}
export function createCombatGraphics(scene,camera,state,settings){
 const group=new T.Group();scene.add(group);const enemyMeshes=new Map(),projectileMeshes=new Map(),effects=[];let heldId='',heldClass='',heldModel=null,swing=0,castFlash=0,hurt=0;
 const hands=new T.Group();camera.add(hands);scene.add(camera);hands.position.set(.36,-.4,-.66);const offhand=new T.Group();offhand.position.set(-.32,-.35,-.55);camera.add(offhand);const glow=orb(offhand,mat(0xb9a2ff,.1,2),0,.11,-.1,.035);const handLight=new T.PointLight(0xc4a2ff,0,3);offhand.add(handLight);
 const ward=new T.Mesh(new T.SphereGeometry(1.18,24,12),new T.MeshBasicMaterial({color:0xaaaaff,transparent:true,opacity:.09,wireframe:true,depthWrite:false}));scene.add(ward);
 const wisp=new T.Group();orb(wisp,mat(0x9cf4df,0,2),0,0,0,.13);meshHalo(wisp,.25,0x8bdccb);scene.add(wisp);
 const sharedParticle=new T.IcosahedronGeometry(1,0),trailGeometry=new T.SphereGeometry(1,8,6);
 function meshHalo(parent,r,color){const m=new T.Mesh(new T.TorusGeometry(r,.015,6,30),mat(color,0,1.5));parent.add(m);return m;}
 function addEffect(object,lifetime,kind='fade',data={}){group.add(object);effects.push({object,lifetime,total:lifetime,kind,...data});while(effects.length>80){const e=effects.shift();disposeEffect(e);}}
 function disposeEffect(e){e.object.removeFromParent();const materials=new Set();e.object.traverse(m=>{if(m.geometry&&m.geometry!==sharedParticle&&m.geometry!==trailGeometry)m.geometry.dispose();if(m.material&&!m.userData.shared)materials.add(m.material);});for(const m of materials)m.dispose();}
 function burst(x,y,z,color,radius){const g=new T.Group();g.position.set(x,y,z);const material=new T.MeshBasicMaterial({color,transparent:true,opacity:.9,depthWrite:false});for(let i=0;i<18;i++){const p=new T.Mesh(sharedParticle,material);const a=i/18*6.28;p.position.set(Math.cos(a)*.1,(i%5)*.08,Math.sin(a)*.1);p.scale.setScalar(.045+radius*.015);p.userData.velocity=new T.Vector3(Math.cos(a)*radius,(i%5)*radius*.3+.5,Math.sin(a)*radius);g.add(p);}addEffect(g,.65,'particles');}
 function ring(e){const g=new T.Group();g.position.set(e.x,e.y??surfaceAt(e.x,e.z)+.12,e.z);const material=new T.MeshBasicMaterial({color:e.color,transparent:true,opacity:.8,side:T.DoubleSide,depthWrite:false});const r=new T.Mesh(new T.RingGeometry(.93,1,64),material);r.rotation.x=-Math.PI/2;g.add(r);if(e.type==='roots')for(let i=0;i<16;i++){const a=i/16*6.28;const stalk=new T.Mesh(new T.ConeGeometry(.07,1,6),material);stalk.position.set(Math.cos(a)*.8,.4,Math.sin(a)*.8);g.add(stalk);}addEffect(g,e.duration||.7,'ring',{radius:e.radius||3});}
 function emit(e){if(e.type==='swing'){swing=1;return;}if(e.type==='cast'){castFlash=1;glow.material=mat(e.color,0,2);handLight.color.setHex(e.color);return;}if(e.type==='hurt'){if(e.amount>0)hurt=.5;return;}if(e.type==='clear'){for(const effect of effects)disposeEffect(effect);effects.length=0;for(const m of projectileMeshes.values())m.removeFromParent();projectileMeshes.clear();return;}if(e.type==='hit'||e.type==='burst'){burst(e.x,e.y,e.z,e.color,e.radius||.4);return;}if(e.type==='ring'||e.type==='roots'){ring(e);return;}
  if(e.type==='lightning'){const points=[],a=new T.Vector3(e.from.x,e.from.y,e.from.z),b=new T.Vector3(e.to.x,e.to.y,e.to.z);for(let i=0;i<=12;i++){const p=a.clone().lerp(b,i/12);if(i>0&&i<12){p.x+=(Math.random()-.5)*.6;p.y+=(Math.random()-.5)*.5;p.z+=(Math.random()-.5)*.6;}points.push(p);}const line=new T.Line(new T.BufferGeometry().setFromPoints(points),new T.LineBasicMaterial({color:e.color,transparent:true,opacity:1}));addEffect(line,.24);return;}
  if(e.type==='meteor'){ring({...e,type:'ring',radius:e.radius,duration:e.duration});const m=new T.Mesh(new T.IcosahedronGeometry(.8,1),new T.MeshBasicMaterial({color:e.color}));m.position.set(e.x,e.y+19,e.z);addEffect(m,e.duration,'meteor',{floor:e.y});return;}
  if(e.type==='blizzard'){const g=new T.Group();g.position.set(e.x,e.y,e.z);const material=new T.MeshBasicMaterial({color:e.color,transparent:true,opacity:.8});for(let i=0;i<65;i++){const p=new T.Mesh(sharedParticle,material);const a=i*2.4,r=Math.sqrt(i/65)*e.radius;p.position.set(Math.cos(a)*r,Math.random()*4,Math.sin(a)*r);p.scale.setScalar(.055);g.add(p);}addEffect(g,e.duration,'snow');}
 }
 function refreshWeapon(){const h=state().hero;if(heldId===h.equipped&&heldClass===h.archetype)return;heldId=h.equipped;heldClass=h.archetype;if(heldModel)disposeModel(heldModel);for(const child of [...hands.children])child.removeFromParent();heldModel=weaponModel(h.equipped);heldModel.scale.setScalar(h.equipped==='crossbow'?.7:.48);hands.add(heldModel);const skin=h.archetype==='ogre'?0x8b9d64:0xc59e7a;orb(heldModel,skin,0,.05,.04,.075,.1,.055);rod(heldModel,h.archetype==='wizard'?0x564378:0x484b40,0,-.1,.05,.067,.18);heldModel.traverse(o=>{if(o.isMesh)o.castShadow=false;});offhand.children.filter(c=>c.userData.hand).forEach(c=>c.removeFromParent());const hand=orb(offhand,skin,0,0,0,.057,.09,.045);hand.userData.hand=true;}
 function syncEnemies(enemies,time){const ids=new Set(enemies.map(e=>e.id));for(const [id,g]of enemyMeshes)if(!ids.has(id)){disposeModel(g);enemyMeshes.delete(id);}for(const e of enemies){let g=enemyMeshes.get(e.id);if(!g){g=enemyModel(e.kind);group.add(g);enemyMeshes.set(e.id,g);}g.visible=!e.dead;const moved=Math.hypot(g.position.x-e.x,g.position.z-e.z)>.002;for(let i=0;i<(g.userData.legs||[]).length;i++)g.userData.legs[i].rotation.x=moved?Math.sin(time*9+i*Math.PI)*.32:0;for(let i=0;i<(g.userData.arms||[]).length;i++)g.userData.arms[i].rotation.x=e.attackTime>.9?-Math.sin((e.attackTime-.9)*5)*.7:moved?Math.sin(time*9+i*Math.PI)*.2:0;g.position.set(e.x,surfaceAt(e.x,e.z),e.z);g.rotation.y=e.heading;if(e.kind==='wraith')g.position.y+=.14+Math.sin(e.x+time*2)*.12;}}
 function update(dt,time,combat,playing,paused,moving){const h=state().hero,p=state().position;refreshWeapon();hands.visible=offhand.visible=playing;const tick=paused?0:dt;swing=Math.max(0,swing-tick*3.6);castFlash=Math.max(0,castFlash-tick*2.7);hurt=Math.max(0,hurt-tick);const t=Math.sin(swing*Math.PI);hands.rotation.set(-t*1.1,0,-.18-t*.8);hands.position.x=combat.blocking?.02:.36;hands.position.y=-.4+t*.05+(!settings.reducedMotion&&moving?Math.sin(time*8)*.008:0);hands.position.z=-.66;offhand.rotation.z=castFlash*.5;glow.scale.setScalar(1+castFlash*4);handLight.intensity=castFlash*3;ward.visible=playing&&h.effects.ward>0&&h.shield>0;ward.position.set(p.x,surfaceAt(p.x,p.z)+1,p.z);ward.rotation.y=time*.3;wisp.visible=playing&&h.effects.wisp>0;wisp.position.set(p.x+Math.cos(time*1.4),surfaceAt(p.x,p.z)+2.2+Math.sin(time*2)*.2,p.z+Math.sin(time*1.4));
  const damageOverlay=document.querySelector('#damage-overlay');if(damageOverlay)damageOverlay.style.opacity=String(hurt*.7);syncEnemies(combat.enemies,time);
  const ids=new Set();for(const p of combat.projectiles){ids.add(p.id);let m=projectileMeshes.get(p.id);if(!m){m=new T.Group();const shot=orb(m,mat(p.color,0,2),0,0,0,p.weapon==='longbow'||p.weapon==='crossbow'?.045:.13);if(p.weapon==='longbow'||p.weapon==='crossbow')cube(m,0xb3a482,0,0,0,.02,.02,.6);group.add(m);projectileMeshes.set(p.id,m);}m.position.set(p.x,p.y,p.z);m.lookAt(p.x+p.dx,p.y+p.dy,p.z+p.dz);}for(const [id,m]of projectileMeshes)if(!ids.has(id)){m.removeFromParent();projectileMeshes.delete(id);}
  for(let i=effects.length-1;i>=0;i--){const e=effects[i];e.lifetime-=tick;const ratio=Math.max(0,e.lifetime/e.total);if(e.kind==='particles')for(const p of e.object.children)p.position.addScaledVector(p.userData.velocity,tick);if(e.kind==='ring')e.object.scale.setScalar(e.radius*(1-ratio*.82));if(e.kind==='meteor')e.object.position.y=e.floor+ratio*19;if(e.kind==='snow'){e.object.rotation.y+=tick*.25;for(const p of e.object.children){p.position.y-=tick*2;if(p.position.y<0)p.position.y=4;}}e.object.traverse(m=>{if(m.material?.transparent)m.material.opacity=ratio*.8;});if(e.lifetime<=0){disposeEffect(e);effects.splice(i,1);}}
 }
 return{emit,update,refreshWeapon,enemyMeshes};
}
